#!/usr/bin/env python3
"""Generate every pillar-csi brand asset from one source of geometry.

Writes the kit under assets/brand/ and copies the serving files into
site/public/ so the two stay byte-identical.

Needs the resvg and usvg binaries on PATH:

  nix shell nixpkgs#resvg --command python3 assets/brand/build.py

The only font is Archivo (variable, wdth and wght axes). By default the script
downloads it from google/fonts at a pinned commit into the user cache and
checks its SHA-256; pass --font-file to use a local copy. Only the Python
standard library is used.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.sax.saxutils import escape

HERE = Path(__file__).resolve().parent          # assets/brand
KIT = HERE
REPO = HERE.parents[1]                           # repo root (…/web)
PUBLIC = REPO / "site" / "public"
DOCS_OG = REPO / "docs" / "social-preview" / "pillar-csi-og.png"

# ---------------------------------------------------------------- palette
#
# "Workshop Enamel". Keep in sync with site/src/styles/global.css and
# palette/tokens.json (generated below).
PALETTE = [
    # key, name, hex, role
    ("enamel",     "Deep Enamel",   "#15352B", "dark ground: landing, docs, social cards"),
    ("green",      "Machine Green", "#2D5F4C", "brand field: icon tiles, avatar, buttons and badges on light"),
    ("cream",      "Enamel Cream",  "#F1EAD6", "text on green; top plate and lit strip on dark"),
    ("steel",      "Steel",         "#AFBAB2", "shaft on dark; muted text on dark"),
    ("brass",      "Brass",         "#D4A849", "the one accent on dark: collar, kernel target, primary action"),
    ("brass-deep", "Brass Deep",    "#8A6414", "brass on white, safe for text"),
    ("ink",        "Ink",           "#112A23", "text on white"),
]
HEX = {k: h for k, _, h, _ in PALETTE}

# Supporting shades that are not named palette colors.
FOOT_DARK = ("#93A097", "#76857B")
FOOT_LIGHT = ("#1F4739", "#15352B")
COLLAR_LIGHT = "#A87B1F"
SHINE_LIGHT = "#5E8C78"
SHINE_LIGHT_SMALL = "#6E9A86"
LINE = "#3C6B5A"          # hairlines and frames on the dark ground
SURFACE = "#1C4336"       # raised surface on the dark ground
PAPER = "#FFFFFF"
CHALK = "#F4F1E8"         # light surface below white

DEEP_ENAMEL, MACHINE_GREEN, ENAMEL_CREAM, STEEL = (
    HEX["enamel"], HEX["green"], HEX["cream"], HEX["steel"])
BRASS, BRASS_DEEP, INK = HEX["brass"], HEX["brass-deep"], HEX["ink"]

SUBTITLE = (
    "One Kubernetes CSI driver for your storage pools.",
    "ZFS and LVM over kernel NVMe-oF/TCP today, more protocols planned.",
)

FONT_URL = (
    "https://raw.githubusercontent.com/google/fonts/"
    "95f4904fc8bcf26d3420fe315560c96417c6dec7/ofl/archivo/Archivo%5Bwdth%2Cwght%5D.ttf"
)
FONT_SHA256 = "0e094a7d3c7c4c25cf1310c4b30014f1dae9332220b1c2c88f4fa996f0b05053"

SVG_NS = "http://www.w3.org/2000/svg"
GEN_NOTE = "Generated by assets/brand/build.py; edit the script, not this file."

# ---------------------------------------------------------------- mark geometry
#
# A column turned from one steel bar, as on a pillar drill: a flat top plate,
# a brass collar, the shaft with one lit strip, and a stepped cast foot.
# 64-unit canvas, every edge on an even unit, so it renders crisp at 32 px.
# (part, x, y, w, h, corner radius)
MARK = (
    ("cap", 14, 4, 36, 6, 2),
    ("collar", 20, 12, 24, 6, 2),
    ("shaft", 24, 20, 16, 30, 0),
    ("shine", 26, 20, 4, 30, 0),
    ("foot", 18, 50, 28, 4, 1),
    ("base", 12, 56, 40, 4, 1.4),
)

# The same column redrawn on a 16-unit grid for favicons: whole pixels only,
# one foot step, a narrower collar.
SMALL = (
    ("cap", 3, 1, 10, 2, 0.6),
    ("collar", 5, 4, 6, 2, 0),
    ("shaft", 6, 6, 4, 7, 0),
    ("shine", 6, 6, 1, 7, 0),
    ("base", 2, 13, 12, 2, 0.6),
)

ON_DARK = {
    "cap": ENAMEL_CREAM, "collar": BRASS, "shaft": STEEL, "shine": ENAMEL_CREAM,
    "foot": FOOT_DARK[0], "base": FOOT_DARK[1],
}
ON_LIGHT = {
    "cap": MACHINE_GREEN, "collar": COLLAR_LIGHT, "shaft": MACHINE_GREEN,
    "shine": SHINE_LIGHT, "foot": FOOT_LIGHT[0], "base": DEEP_ENAMEL,
}
# At 16 px the lit strip is one pixel wide, so it is lighter on white; the
# single foot is lighter on dark for separation from the shaft.
SMALL_ON_DARK = {**ON_DARK, "base": "#8C998F"}
SMALL_ON_LIGHT = {**ON_LIGHT, "shine": SHINE_LIGHT_SMALL}
MONO_BLACK = {p: "#000000" for p, *_ in MARK}
MONO_WHITE = {p: "#FFFFFF" for p, *_ in MARK}
MONO_CURRENT = {p: "currentColor" for p, *_ in MARK}


def shapes(geometry, colors, classes: bool = False) -> str:
    out = []
    for part, x, y, w, h, r in geometry:
        cls = f' class="pc-{part}"' if classes else ""
        rx = f' rx="{r:g}"' if r else ""
        out.append(f'<rect{cls} x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}"{rx} fill="{colors[part]}"/>')
    return "".join(out)


def mark(x: float, y: float, size: float, colors=ON_DARK) -> str:
    """The 64-unit mark drawn size px tall with its origin at (x, y)."""
    return f'<g transform="translate({x:g} {y:g}) scale({size / 64:g})">{shapes(MARK, colors)}</g>'


# ---------------------------------------------------------------- helpers


def need(binary: str) -> str:
    path = shutil.which(binary)
    if not path:
        sys.exit(f"{binary} not found on PATH; run via `nix shell nixpkgs#resvg --command ...`")
    return path


def fetch_font(explicit: Path | None) -> Path:
    if explicit:
        return explicit
    cache = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache")) / "pillar-csi"
    path = cache / f"Archivo-{FONT_SHA256[:12]}.ttf"
    if not path.exists():
        cache.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(FONT_URL) as resp:
            data = resp.read()
        if hashlib.sha256(data).hexdigest() != FONT_SHA256:
            sys.exit(f"Archivo download from {FONT_URL} does not match the pinned SHA-256")
        path.write_bytes(data)
    return path


def font_args(font: Path) -> list[str]:
    return ["--skip-system-fonts", "--use-font-file", str(font)]


def text(x: float, y: float, s: str, size: float, fill: str, weight: int = 400,
         anchor: str = "start", stretch: str = "normal", spacing: float = 0) -> str:
    return (
        f'<text x="{x:g}" y="{y:g}" font-family="Archivo" font-size="{size:g}" '
        f'font-weight="{weight}" font-stretch="{stretch}" fill="{fill}" '
        f'text-anchor="{anchor}" letter-spacing="{spacing:g}">{escape(s)}</text>'
    )


def render(svg: str, out: Path, font: Path, width: int | None = None,
           height: int | None = None) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as fh:
        fh.write(svg)
        src = fh.name
    cmd = [need("resvg"), *font_args(font)]
    if width:
        cmd += ["-w", str(width)]
    if height:
        cmd += ["-h", str(height)]
    subprocess.run([*cmd, src, str(out)], check=True)
    Path(src).unlink()


def svg_doc(w: float, h: float, body: str, vb: str | None = None) -> str:
    return (
        f'<svg xmlns="{SVG_NS}" viewBox="{vb or f"0 0 {w:g} {h:g}"}" width="{w:g}" height="{h:g}" '
        f'role="img" aria-label="pillar-csi"><title>pillar-csi</title>\n'
        f"<!-- {GEN_NOTE} -->\n{body}\n</svg>\n"
    )


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


# ---------------------------------------------------------------- wordmark
#
# "pillar-csi" in Archivo Bold at width 125 (Expanded), tracking -0.01em,
# outlined by usvg. wordmark_geometry returns the raw path (baseline at 0)
# plus its bounds, so each lockup can place it exactly.
WORD_SIZE = 36
WORD_GAP = 16
WORD_TRACKING = -0.01  # em


def wordmark_geometry(font: Path) -> tuple[str, float, float, float]:
    """Outline the wordmark. Returns (path data, advance width, top, bottom)."""
    probe = (
        f'<svg xmlns="{SVG_NS}" width="400" height="64" viewBox="0 0 400 64">'
        + text(0, 0, "pillar-csi", WORD_SIZE, "#000", 700, stretch="expanded",
               spacing=WORD_SIZE * WORD_TRACKING)
        + "</svg>"
    )
    with tempfile.TemporaryDirectory() as tmp:
        inp, out = Path(tmp, "in.svg"), Path(tmp, "out.svg")
        inp.write_text(probe)
        subprocess.run([need("usvg"), *font_args(font), "--coordinates-precision", "2", str(inp), str(out)], check=True)
        paths = [p.get("d") for p in ET.parse(out).iter(f"{{{SVG_NS}}}path")]
    if not paths:
        sys.exit("usvg produced no outlines for the wordmark; check the font file")
    d = " ".join(paths)
    nums = [float(n) for n in re.findall(r"-?\d+(?:\.\d+)?", d)]
    xs, ys = nums[0::2], nums[1::2]
    return d, max(xs), min(ys), max(ys)


def shift_d(d: str, dx: float, dy: float) -> str:
    return re.sub(
        r"(-?\d+(?:\.\d+)?) (-?\d+(?:\.\d+)?)",
        lambda m: f"{float(m.group(1)) + dx:g} {float(m.group(2)) + dy:.2f}",
        d,
    )


def wordmark_at(x: float, baseline: float, wm: tuple, ink: str) -> str:
    d, w, _, _ = wm
    return f'<path transform="translate({x:g} {baseline:.2f})" fill="{ink}" d="{d}"/>'


# ---------------------------------------------------------------- SVG assets


def mark_svg(colors) -> str:
    return svg_doc(64, 64, shapes(MARK, colors))


def lockup_horizontal(wm, colors, ink: str) -> str:
    d, w, top, _ = wm
    shift = 32 - top / 2
    placed = shift_d(d, 64 + WORD_GAP, shift)
    width = round(64 + WORD_GAP + w + 2)
    return svg_doc(width, 64, shapes(MARK, colors) + f'\n<path fill="{ink}" d="{placed}"/>')


def lockup_stacked(wm, colors, ink: str) -> str:
    """Mark over wordmark, centered; the wordmark runs at the same 36px but the
    canvas is wider, so the pair reads as one block."""
    d, w, top, _ = wm
    mark_w = 64
    width = round(max(mark_w, w) + 16)
    mx = (width - mark_w) / 2
    baseline = 64 + 24 - top
    placed = shift_d(d, (width - w) / 2, baseline)
    body = f'<g transform="translate({mx:g} 0)">{shapes(MARK, colors)}</g>'
    body += f'\n<path fill="{ink}" d="{placed}"/>'
    return svg_doc(width, round(64 + 24 + 0 - top + 2), body)


def wordmark_only(wm, ink: str) -> str:
    d, w, top, bottom = wm
    placed = shift_d(d, 0, -top)
    return svg_doc(round(w + 2), round(-top + bottom + 2), f'<path fill="{ink}" d="{placed}"/>')


def favicon_svg() -> str:
    """White-ground colors by default; dark browser chrome swaps to the on-dark set."""
    drawn = {part for part, *_ in SMALL}
    rules = " ".join(f".pc-{p} {{ fill: {c}; }}" for p, c in SMALL_ON_DARK.items() if p in drawn)
    body = (
        f"<style>@media (prefers-color-scheme: dark) {{ {rules} }}</style>\n"
        + shapes(SMALL, SMALL_ON_LIGHT, classes=True)
    )
    return svg_doc(16, 16, body)


def tile_svg(size: int, radius_ratio: float = 3 / 16, pad_ratio: float = 0) -> str:
    """Mark on a Machine Green rounded tile. pad_ratio shrinks the mark toward the
    center for maskable icons. 16 and 48 px use the 16-unit drawing; other sizes
    use the full mark scaled to a whole-pixel fit."""
    radius = round(size * radius_ratio)
    inner = round(size * (1 - pad_ratio))
    off = (size - inner) / 2
    if inner % 16 == 0 and size in (16, 48):
        art = f'<g transform="translate({off:g} {off:g}) scale({inner / 16:g})">{shapes(SMALL, SMALL_ON_DARK)}</g>'
    else:
        # scale the 64-unit mark so every edge still lands on a whole pixel
        s = inner / 64
        art = f'<g transform="translate({off:g} {off:g}) scale({s:g})">{shapes(MARK, ON_DARK)}</g>'
    return (
        f'<svg xmlns="{SVG_NS}" width="{size}" height="{size}" viewBox="0 0 {size} {size}">'
        f'<rect width="{size}" height="{size}" rx="{radius:g}" fill="{MACHINE_GREEN}"/>{art}</svg>'
    )


def apple_touch_icon() -> str:
    # iOS rounds the corners itself, so the ground is a full square; 2x keeps edges whole.
    return (
        f'<svg xmlns="{SVG_NS}" width="180" height="180" viewBox="0 0 180 180">'
        f'<rect width="180" height="180" fill="{MACHINE_GREEN}"/>{mark(26, 26, 128)}</svg>'
    )


def avatar_svg(size: int = 500) -> str:
    """GitHub avatar: Machine Green rounded square, circle-safe mark."""
    inner = round(size * 0.62)
    off = (size - inner) / 2
    return (
        f'<svg xmlns="{SVG_NS}" width="{size}" height="{size}" viewBox="0 0 {size} {size}">'
        f'<rect width="{size}" height="{size}" rx="{round(size * 0.2):g}" fill="{MACHINE_GREEN}"/>'
        f'{mark(off, off, inner)}</svg>'
    )


def banner(wm, dark: bool) -> str:
    """1280x320 README banner. Centered horizontal lockup; ground fills the whole frame."""
    w, h = 1280, 320
    bg, ink, colors, sub = (DEEP_ENAMEL, ENAMEL_CREAM, ON_DARK, STEEL) if dark else \
        (CHALK, INK, ON_LIGHT, "#51615A")
    d, ww, top, _ = wm
    lock_w = 64 + WORD_GAP + ww
    scale = 112 / 64
    lw = lock_w * scale
    lx, ly = (w - lw) / 2, 78
    placed = shift_d(d, 0, 0)
    parts = [
        f'<rect width="{w}" height="{h}" fill="{bg}"/>',
        f'<g transform="translate({lx:g} {ly:g}) scale({scale:g})">{shapes(MARK, colors)}',
        f'<path transform="translate({64 + WORD_GAP} {32 - top / 2:.2f})" fill="{ink}" d="{placed}"/></g>',
        text(w / 2, 260, "Kubernetes CSI driver: ZFS and LVM from one storage node, over NVMe-oF/TCP.",
             30, sub, 500, anchor="middle"),
    ]
    return svg_doc(w, h, "".join(parts))


def palette_sheet() -> str:
    """Swatch sheet: every named color with hex, role, and WCAG ratio on both grounds."""
    w, row_h, pad = 880, 96, 24
    h = pad + len(PALETTE) * (row_h + 12) + pad + 40
    parts = [f'<rect width="{w}" height="{h}" fill="{PAPER}"/>',
             text(pad, pad + 4, "pillar-csi · Workshop Enamel", 20, INK, 700)]
    y = pad + 40
    for key, name, hx, role in PALETTE:
        light_txt = INK if key in ("cream", "steel", "brass") else ENAMEL_CREAM
        parts.append(f'<rect x="{pad}" y="{y}" width="200" height="{row_h}" rx="10" fill="{hx}"/>')
        if hx == PAPER:
            parts.append(f'<rect x="{pad}" y="{y}" width="200" height="{row_h}" rx="10" fill="none" stroke="#D8D3C4"/>')
        parts.append(text(pad + 16, y + 34, name, 16, light_txt, 700))
        parts.append(text(pad + 16, y + 62, hx, 14, light_txt, 400))
        parts.append(text(pad + 224, y + 34, role, 15, "#51615A", 400))
        r_w = contrast(hx, PAPER)
        r_d = contrast(hx, DEEP_ENAMEL)
        parts.append(text(pad + 224, y + 62, f"{r_w:.1f}:1 on white · {r_d:.1f}:1 on dark", 13, "#7A827A", 400))
        y += row_h + 12
    return svg_doc(w, y + pad, "".join(parts))


def lum(h: str) -> float:
    h = h.lstrip("#")
    c = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4 for v in c]
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def contrast(a: str, b: str) -> float:
    la, lb = sorted((lum(a), lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


# ---------------------------------------------------------------- social cards


def arrow(x1: float, y1: float, x2: float, y2: float, color: str) -> str:
    dx, dy = (x2 > x1) - (x2 < x1), (y2 > y1) - (y2 < y1)
    bx, by = x2 - 14 * dx, y2 - 14 * dy
    px, py = 8 * dy, 8 * dx
    return (
        f'<line x1="{x1:g}" y1="{y1:g}" x2="{bx:g}" y2="{by:g}" stroke="{color}" stroke-width="3"/>'
        f'<path d="M{bx + px:g} {by + py:g} L{x2:g} {y2:g} L{bx - px:g} {by - py:g} Z" fill="{color}"/>'
    )


def frame(x: float, y: float, w: float, h: float, label: str) -> str:
    return (
        f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" rx="14" fill="none" '
        f'stroke="{LINE}" stroke-width="2" stroke-dasharray="8 7"/>'
        + text(x + 24, y + 36, label, 17, STEEL, 500)
    )


def node(x: float, y: float, w: float, h: float, label: str, stroke: str, sw: float = 1.5) -> str:
    return (
        f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" rx="10" fill="{SURFACE}" '
        f'stroke="{stroke}" stroke-width="{sw:g}"/>'
        + text(x + w / 2, y + h / 2 + 7, label, 20, ENAMEL_CREAM, 500, anchor="middle")
    )


def card_content(url: str, wm) -> str:
    """Card content in 1280x640 design space. Safe zone: x 80..1200, y 80..560."""
    d, w, top, _ = wm
    lock_h = 76
    placed = shift_d(d, 0, 0)
    parts = [
        f'<g transform="translate(80 104) scale({lock_h / 64:g})">'
        f'{shapes(MARK, ON_DARK)}'
        f'<path transform="translate({64 + WORD_GAP} {32 - top / 2:.2f})" fill="{ENAMEL_CREAM}" d="{placed}"/></g>'
    ]
    lines = [
        ("One Kubernetes CSI driver", ENAMEL_CREAM),
        ("for your storage pools.", ENAMEL_CREAM),
        ("ZFS and LVM over kernel", STEEL),
        ("NVMe-oF/TCP today, more", STEEL),
        ("protocols planned.", STEEL),
    ]
    y = 262
    for s, color in lines:
        parts.append(text(80, y, s, 31, color, 500))
        y += 44
    parts.append(text(80, 540, url, 20, STEEL, 400))

    # Data path, storage to Pod, shipped features only. Cream is the path;
    # brass marks the kernel target, the same role as the collar in the mark.
    parts.append(frame(700, 88, 500, 180, "storage node"))
    parts.append(node(726, 150, 206, 84, "ZFS zvol / LVM LV", STEEL))
    parts.append(node(976, 150, 188, 84, "kernel nvmet", BRASS, 3))
    parts.append(arrow(932, 192, 976, 192, ENAMEL_CREAM))
    parts.append(frame(700, 372, 500, 180, "worker node"))
    parts.append(node(952, 438, 236, 84, "/dev/nvmeXnY in a Pod", STEEL))
    parts.append(arrow(1070, 234, 1070, 438, ENAMEL_CREAM))
    parts.append(text(1054, 342, "NVMe-oF/TCP", 17, STEEL, 500, anchor="end"))
    return "".join(parts)


def card(w: int, h: int, url: str, wm) -> str:
    scale = min(w / 1280, h / 640)
    dx, dy = (w - 1280 * scale) / 2, (h - 640 * scale) / 2
    return (
        f'<svg xmlns="{SVG_NS}" width="{w}" height="{h}" viewBox="0 0 {w} {h}">'
        f'<rect width="{w}" height="{h}" fill="{DEEP_ENAMEL}"/>'
        f'<g transform="translate({dx:g} {dy:g}) scale({scale:g})">{card_content(url, wm)}</g>'
        f"</svg>"
    )


def write_ico(pngs: list[tuple[int, bytes]], out: Path) -> None:
    header = struct.pack("<HHH", 0, 1, len(pngs))
    offset = len(header) + 16 * len(pngs)
    entries, blobs = b"", b""
    for size, data in pngs:
        entries += struct.pack("<BBBBHHII", size % 256, size % 256, 0, 0, 1, 32, len(data), offset)
        offset += len(data)
        blobs += data
    out.write_bytes(header + entries + blobs)


# ---------------------------------------------------------------- tokens


def tokens_json() -> str:
    doc = {
        "$comment": GEN_NOTE,
        "name": "Workshop Enamel",
        "colors": {
            k: {"hex": h, "name": n, "role": r} for k, n, h, r in PALETTE
        },
        "shades": {
            "foot-dark": FOOT_DARK, "foot-light": FOOT_LIGHT,
            "collar-light": COLLAR_LIGHT, "shine-light": SHINE_LIGHT,
            "shine-light-small": SHINE_LIGHT_SMALL,
            "line": LINE, "surface": SURFACE, "chalk": CHALK,
        },
    }
    return json.dumps(doc, indent=2) + "\n"


def webmanifest_json() -> str:
    doc = {
        "name": "pillar-csi",
        "short_name": "pillar-csi",
        "description": (
            "One Kubernetes CSI driver for ZFS and LVM pools, "
            "served over kernel NVMe-oF/TCP."
        ),
        "start_url": "/",
        "scope": "/",
        "display": "browser",
        "theme_color": DEEP_ENAMEL,
        "background_color": DEEP_ENAMEL,
        "icons": [
            {"src": "/icon-192.png", "sizes": "192x192",
             "type": "image/png", "purpose": "any"},
            {"src": "/icon-512.png", "sizes": "512x512",
             "type": "image/png", "purpose": "any"},
            {"src": "/icon-maskable-512.png", "sizes": "512x512",
             "type": "image/png", "purpose": "maskable"},
        ],
    }
    return json.dumps(doc, indent=2) + "\n"


def palette_css() -> str:
    lines = [f"/* {GEN_NOTE} */", ":root {"]
    for key, name, hx, role in PALETTE:
        lines.append(f"  --pillar-{key}: {hx}; /* {name} — {role} */")
    for key, val in (("line", LINE), ("surface", SURFACE), ("chalk", CHALK)):
        lines.append(f"  --pillar-{key}: {val};")
    lines.append("}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- build


def outline_text(svg: str, font: Path) -> str:
    """Convert <text> to paths with usvg so the SVG renders without the font."""
    with tempfile.TemporaryDirectory() as tmp:
        inp, out = Path(tmp, "in.svg"), Path(tmp, "out.svg")
        inp.write_text(svg)
        subprocess.run([need("usvg"), *font_args(font), "--coordinates-precision", "2", str(inp), str(out)], check=True)
        return out.read_text()


def build(font: Path) -> dict[str, Path]:
    """Write every kit file and the site/public copies. Returns path -> svg for contact sheet."""
    wm = wordmark_geometry(font)
    svgd = {}

    def put(rel: str, svg: str):
        svgd[rel] = svg

    # mark/
    put("mark/mark-color-dark.svg", mark_svg(ON_DARK))
    put("mark/mark-color-light.svg", mark_svg(ON_LIGHT))
    put("mark/mark-mono-black.svg", mark_svg(MONO_BLACK))
    put("mark/mark-mono-white.svg", mark_svg(MONO_WHITE))
    put("mark/mark-mono-currentcolor.svg", mark_svg(MONO_CURRENT))

    # logo/
    put("logo/logo-horizontal-dark.svg", lockup_horizontal(wm, ON_DARK, ENAMEL_CREAM))
    put("logo/logo-horizontal-light.svg", lockup_horizontal(wm, ON_LIGHT, INK))
    put("logo/logo-horizontal-mono.svg", lockup_horizontal(wm, MONO_BLACK, "#000000"))
    put("logo/logo-stacked-dark.svg", lockup_stacked(wm, ON_DARK, ENAMEL_CREAM))
    put("logo/logo-stacked-light.svg", lockup_stacked(wm, ON_LIGHT, INK))
    put("logo/wordmark-dark.svg", wordmark_only(wm, ENAMEL_CREAM))
    put("logo/wordmark-light.svg", wordmark_only(wm, INK))

    # icon/
    put("icon/icon-app.svg", avatar_svg(500))

    # social/
    put("social/social-github.svg", card(1280, 640, "github.com/isac322/pillar-csi", wm))
    put("social/og.svg", card(1200, 630, "pillar-csi.bhyoo.com", wm))
    put("social/readme-banner-dark.svg", banner(wm, True))
    put("social/readme-banner-light.svg", banner(wm, False))

    # favicon/
    put("favicon/favicon.svg", favicon_svg())

    # palette/
    write(KIT / "palette" / "tokens.json", tokens_json())
    write(KIT / "palette" / "palette.css", palette_css())
    put("palette/palette.svg", palette_sheet())

    # write SVGs; text-bearing files go through usvg so they ship path-only
    TEXT_BEARING = {"social/", "palette/"}
    for rel, svg in svgd.items():
        if rel.split("/")[0] + "/" in TEXT_BEARING:
            svg = outline_text(svg, font)
            if GEN_NOTE not in svg:
                svg = svg.replace("<svg", f"<!-- {GEN_NOTE} -->\n<svg", 1)
            svgd[rel] = svg
        write(KIT / rel, svg)

    # rasters
    render(svgd["social/social-github.svg"], KIT / "social" / "pillar-csi-og.png", font)
    render(svgd["social/og.svg"], KIT / "social" / "og.png", font)
    render(svgd["icon/icon-app.svg"], KIT / "icon" / "avatar-github.png", font, width=500)
    render(apple_touch_icon(), KIT / "favicon" / "apple-touch-icon.png", font)
    for size in (192, 512):
        render(tile_svg(size), KIT / "favicon" / f"icon-{size}.png", font, width=size)
    render(tile_svg(512, radius_ratio=0.12, pad_ratio=0.2),
           KIT / "favicon" / "icon-maskable-512.png", font, width=512)

    pngs = []
    with tempfile.TemporaryDirectory() as tmp:
        for size in (16, 32, 48):
            out = Path(tmp, f"{size}.png")
            render(tile_svg(size), out, font, width=size)
            pngs.append((size, out.read_bytes()))
    write_ico(pngs, KIT / "favicon" / "favicon.ico")

    # site/public copies — identical files
    copies = {
        "site/public/brand/mark.svg": svgd["mark/mark-color-dark.svg"],
        "site/public/brand/mark-light.svg": svgd["mark/mark-color-light.svg"],
        "site/public/brand/logo.svg": svgd["logo/logo-horizontal-dark.svg"],
        "site/public/brand/logo-light.svg": svgd["logo/logo-horizontal-light.svg"],
        "site/public/favicon.svg": svgd["favicon/favicon.svg"],
    }
    for rel, svg in copies.items():
        write(REPO / rel, svg)
    for src, dst in (
        (KIT / "favicon" / "favicon.ico", PUBLIC / "favicon.ico"),
        (KIT / "favicon" / "apple-touch-icon.png", PUBLIC / "apple-touch-icon.png"),
        (KIT / "favicon" / "icon-192.png", PUBLIC / "icon-192.png"),
        (KIT / "favicon" / "icon-512.png", PUBLIC / "icon-512.png"),
        (KIT / "favicon" / "icon-maskable-512.png", PUBLIC / "icon-maskable-512.png"),
        (KIT / "social" / "og.png", PUBLIC / "og.png"),
        (KIT / "social" / "pillar-csi-og.png", DOCS_OG),
    ):
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)
    write(PUBLIC / "site.webmanifest", webmanifest_json())

    return svgd


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--font-file", type=Path, help="local Archivo[wdth,wght].ttf instead of the pinned download")
    args = ap.parse_args()
    font = fetch_font(args.font_file)
    build(font)
    return 0


if __name__ == "__main__":
    sys.exit(main())
