/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package csi

import (
	"context"
	"errors"
	"maps"
	"testing"

	"google.golang.org/grpc/codes"
	corev1 "k8s.io/api/core/v1"
	storagev1 "k8s.io/api/storage/v1"
	"k8s.io/apimachinery/pkg/types"
	ctrlclient "sigs.k8s.io/controller-runtime/pkg/client"

	v1alpha1 "github.com/isac322/pillar-csi/api/v1alpha1"
)

const (
	digestDriver   = "pillar-csi.bhyoo.com"
	digestProtocol = "nvme-digest"
	digestBinding  = "digest-binding"
	digestClass    = "digest-sc"
	digestHostNQN  = "nqn.2014-08.org.nvmexpress:uuid:worker-node-1-digest"
)

// digestProtocolObj is an NVMe/TCP PillarProtocol with the given digests.
func digestProtocolObj(hdr, data bool) *v1alpha1.PillarProtocol {
	return &v1alpha1.PillarProtocol{
		Name: digestProtocol,
		Spec: v1alpha1.PillarProtocolSpec{Protocol: v1alpha1.ProtocolSpec{
			NVMeOFTCP: &v1alpha1.NVMeOFTCPConfig{Port: 4420, HdrDigest: hdr, DataDigest: data},
		}},
	}
}

// digestPV is the PersistentVolume external-provisioner created for the
// publish request's volume, provisioned through StorageClass scName.
func digestPV(volumeID, scName string) *corev1.PersistentVolume {
	return &corev1.PersistentVolume{
		Name: pillarVolumeStateNameFromVolumeID(volumeID),
		Spec: corev1.PersistentVolumeSpec{
			StorageClassName: scName,
			PersistentVolumeSource: corev1.PersistentVolumeSource{CSI: &corev1.CSIPersistentVolumeSource{
				Driver: digestDriver, VolumeHandle: volumeID,
			}},
		},
	}
}

// generatedDigestClass is a StorageClass generated by PillarStorageClass
// digestBinding, which names digestProtocol.
func generatedDigestClass() []ctrlclient.Object {
	return []ctrlclient.Object{
		&storagev1.StorageClass{
			Name:        digestClass,
			Provisioner: digestDriver,
			Parameters:  map[string]string{paramBinding: digestBinding},
		},
		&v1alpha1.PillarStorageClass{
			Name: digestBinding,
			Spec: v1alpha1.PillarStorageClassSpec{StoreRef: testStoreName, ProtocolRef: digestProtocol},
		},
	}
}

// newDigestPublishEnv seeds a publishable NVMe/TCP volume, its node identity
// and objs.
func newDigestPublishEnv(t *testing.T, objs ...ctrlclient.Object) *controllerTestEnv {
	t.Helper()
	volumeID := basePublishRequest().GetVolumeId()
	seed := append([]ctrlclient.Object{
		volumeStateFor(volumeID),
		&storagev1.CSINode{
			Name:        basePublishRequest().GetNodeId(),
			Annotations: map[string]string{AnnotationNVMeOFHostNQN: digestHostNQN},
		},
	}, objs...)
	return newPublishTestEnv(t, seed...)
}

// digestKeys returns the digest entries of a PublishContext.
func digestKeys(pc map[string]string) map[string]string {
	out := map[string]string{}
	for _, k := range []string{PublishContextKeyNVMeOFHdrDigest, PublishContextKeyNVMeOFDataDigest} {
		if v, ok := pc[k]; ok {
			out[k] = v
		}
	}
	return out
}

// TestControllerPublishVolume_NVMeoFDigests verifies that the PublishContext
// carries the digest flags of the volume's current PillarProtocol, found
// through its PersistentVolume's StorageClass (generated or hand-written),
// and nothing when the protocol leaves them off or cannot be found.
func TestControllerPublishVolume_NVMeoFDigests(t *testing.T) {
	t.Parallel()
	volumeID := basePublishRequest().GetVolumeId()
	both := map[string]string{
		PublishContextKeyNVMeOFHdrDigest:  "true",
		PublishContextKeyNVMeOFDataDigest: "true",
	}
	cases := []struct {
		name string
		objs []ctrlclient.Object
		want map[string]string
	}{
		{
			name: "generated class follows PillarStorageClass protocolRef",
			objs: append(generatedDigestClass(), digestProtocolObj(true, true), digestPV(volumeID, digestClass)),
			want: both,
		},
		{
			name: "hand-written class names the protocol",
			objs: []ctrlclient.Object{
				&storagev1.StorageClass{
					Name:        "hand-written",
					Provisioner: digestDriver,
					Parameters:  map[string]string{paramStoreRef: testStoreName, paramProtocolRef: digestProtocol},
				},
				digestProtocolObj(false, true),
				digestPV(volumeID, "hand-written"),
			},
			want: map[string]string{PublishContextKeyNVMeOFDataDigest: "true"},
		},
		{
			name: "digests off",
			objs: append(generatedDigestClass(), digestProtocolObj(false, false), digestPV(volumeID, digestClass)),
			want: map[string]string{},
		},
		{
			name: "no PersistentVolume",
			objs: append(generatedDigestClass(), digestProtocolObj(true, true)),
			want: map[string]string{},
		},
		{
			name: "PersistentVolume of another volume handle",
			objs: append(generatedDigestClass(), digestProtocolObj(true, true),
				digestPV("storage-node-1/nvmeof-tcp/zfs-zvol/tank/other", digestClass)),
			want: map[string]string{},
		},
		{
			name: "StorageClass gone",
			objs: []ctrlclient.Object{digestProtocolObj(true, true), digestPV(volumeID, digestClass)},
			want: map[string]string{},
		},
		{
			name: "PillarProtocol gone",
			objs: append(generatedDigestClass(), digestPV(volumeID, digestClass)),
			want: map[string]string{},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			env := newDigestPublishEnv(t, tc.objs...)
			resp, err := env.srv.ControllerPublishVolume(context.Background(), basePublishRequest())
			if err != nil {
				t.Fatalf("ControllerPublishVolume: %v", err)
			}
			if got := digestKeys(resp.GetPublishContext()); !maps.Equal(got, tc.want) {
				t.Errorf("digest PublishContext = %v, want %v", got, tc.want)
			}
			if env.agent.allowInitiatorCalls != 1 {
				t.Errorf("AllowInitiator calls = %d, want 1", env.agent.allowInitiatorCalls)
			}
		})
	}
}

// TestControllerPublishVolume_NVMeoFDigestsFollowLiveProtocol verifies the
// already-provisioned volume path: the digests are not recorded with the
// volume, so a PillarProtocol change after provisioning reaches the next
// publish, enabling and disabling alike.
func TestControllerPublishVolume_NVMeoFDigestsFollowLiveProtocol(t *testing.T) {
	t.Parallel()
	volumeID := basePublishRequest().GetVolumeId()
	env := newDigestPublishEnv(t,
		append(generatedDigestClass(), digestProtocolObj(false, false), digestPV(volumeID, digestClass))...)
	ctx := context.Background()

	resp, err := env.srv.ControllerPublishVolume(ctx, basePublishRequest())
	if err != nil {
		t.Fatalf("first ControllerPublishVolume: %v", err)
	}
	if got := digestKeys(resp.GetPublishContext()); len(got) != 0 {
		t.Fatalf("digests before enabling = %v, want none", got)
	}

	setDigests := func(hdr, data bool) {
		t.Helper()
		protocol := &v1alpha1.PillarProtocol{}
		if getErr := env.srv.k8sClient.Get(ctx, types.NamespacedName{Name: digestProtocol}, protocol); getErr != nil {
			t.Fatalf("get protocol: %v", getErr)
		}
		protocol.Spec.Protocol.NVMeOFTCP.HdrDigest = hdr
		protocol.Spec.Protocol.NVMeOFTCP.DataDigest = data
		if updateErr := env.srv.k8sClient.Update(ctx, protocol); updateErr != nil {
			t.Fatalf("update protocol: %v", updateErr)
		}
	}

	setDigests(true, true)
	resp, err = env.srv.ControllerPublishVolume(ctx, basePublishRequest())
	if err != nil {
		t.Fatalf("publish after enabling: %v", err)
	}
	want := map[string]string{
		PublishContextKeyNVMeOFHdrDigest:  "true",
		PublishContextKeyNVMeOFDataDigest: "true",
	}
	if got := digestKeys(resp.GetPublishContext()); !maps.Equal(got, want) {
		t.Fatalf("digests after enabling = %v, want %v", got, want)
	}

	setDigests(true, false)
	resp, err = env.srv.ControllerPublishVolume(ctx, basePublishRequest())
	if err != nil {
		t.Fatalf("publish after disabling data digest: %v", err)
	}
	want = map[string]string{PublishContextKeyNVMeOFHdrDigest: "true"}
	if got := digestKeys(resp.GetPublishContext()); !maps.Equal(got, want) {
		t.Fatalf("digests after disabling data digest = %v, want %v", got, want)
	}
}

// failingStorageClassReader fails every StorageClass read with a transient
// API error.
type failingStorageClassReader struct {
	ctrlclient.Reader
}

var errStorageClassUnavailable = errors.New("apiserver unavailable")

func (c failingStorageClassReader) Get(
	ctx context.Context, key ctrlclient.ObjectKey, obj ctrlclient.Object, opts ...ctrlclient.GetOption,
) error {
	if _, ok := obj.(*storagev1.StorageClass); ok {
		return errStorageClassUnavailable
	}
	return c.Reader.Get(ctx, key, obj, opts...)
}

// authoritativeProtocolReader stands in for the API server reader: it
// returns protocol for its name, while the cached client still holds an
// older copy, and delegates every other read.
type authoritativeProtocolReader struct {
	ctrlclient.Reader
	protocol *v1alpha1.PillarProtocol
}

func (r authoritativeProtocolReader) Get(
	ctx context.Context, key ctrlclient.ObjectKey, obj ctrlclient.Object, opts ...ctrlclient.GetOption,
) error {
	if p, ok := obj.(*v1alpha1.PillarProtocol); ok && key.Name == r.protocol.Name {
		r.protocol.DeepCopyInto(p)
		return nil
	}
	return r.Reader.Get(ctx, key, obj, opts...)
}

// TestControllerPublishVolume_NVMeoFDigestsBypassCache verifies the digests
// are read from the API server, not the informer cache: the attacher never
// re-publishes an attached volume, so a publish answered from a cache that
// has not seen a protocol edit yet would leave the attachment without the
// digest for its whole lifetime.
func TestControllerPublishVolume_NVMeoFDigestsBypassCache(t *testing.T) {
	t.Parallel()
	volumeID := basePublishRequest().GetVolumeId()
	env := newDigestPublishEnv(t,
		append(generatedDigestClass(), digestProtocolObj(false, false), digestPV(volumeID, digestClass))...)
	env.srv.apiReader = authoritativeProtocolReader{Reader: env.srv.k8sClient, protocol: digestProtocolObj(true, true)}

	resp, err := env.srv.ControllerPublishVolume(context.Background(), basePublishRequest())
	if err != nil {
		t.Fatalf("ControllerPublishVolume: %v", err)
	}
	want := map[string]string{
		PublishContextKeyNVMeOFHdrDigest:  "true",
		PublishContextKeyNVMeOFDataDigest: "true",
	}
	if got := digestKeys(resp.GetPublishContext()); !maps.Equal(got, want) {
		t.Errorf("digest PublishContext = %v, want the API server's %v (not the stale cache)", got, want)
	}
}

// TestControllerPublishVolume_NVMeoFDigestReadError verifies that a transient
// API error while looking up the protocol fails the publish as Internal
// before any agent call, instead of publishing without a requested digest.
func TestControllerPublishVolume_NVMeoFDigestReadError(t *testing.T) {
	t.Parallel()
	volumeID := basePublishRequest().GetVolumeId()
	env := newDigestPublishEnv(t,
		append(generatedDigestClass(), digestProtocolObj(true, true), digestPV(volumeID, digestClass))...)
	env.srv.apiReader = failingStorageClassReader{Reader: env.srv.k8sClient}

	_, err := env.srv.ControllerPublishVolume(context.Background(), basePublishRequest())
	requireGRPCCode(t, err, codes.Internal)
	if env.agent.allowInitiatorCalls != 0 {
		t.Errorf("AllowInitiator calls = %d, want 0 after a failed protocol read", env.agent.allowInitiatorCalls)
	}
	pvs, _, loadErr := env.srv.loadPillarVolumeState(context.Background(), pillarVolumeStateNameFromVolumeID(volumeID))
	if loadErr != nil {
		t.Fatalf("load PillarVolumeState: %v", loadErr)
	}
	if len(pvs.Status.PublishedNodes) != 0 {
		t.Errorf("publishedNodes = %+v, want none after a failed protocol read", pvs.Status.PublishedNodes)
	}
}

// TestNVMeoFDigestContext_Off verifies a protocol with both digests off
// adds no PublishContext entries.
func TestNVMeoFDigestContext_Off(t *testing.T) {
	t.Parallel()
	if got := nvmeofDigestContext(&v1alpha1.NVMeOFTCPConfig{}); got != nil {
		t.Errorf("digest context with both digests off = %v, want nil", got)
	}
}

// TestCreateVolume_NVMeoFDigestsNotRecorded verifies that CreateVolume keeps
// the digests out of the VolumeContext and the resolved record: they are
// read from the live PillarProtocol at each publish, so a recorded copy
// could only go stale.
func TestCreateVolume_NVMeoFDigestsNotRecorded(t *testing.T) {
	t.Parallel()
	env := newControllerTestEnv(t)
	ctx := context.Background()
	proto := &v1alpha1.PillarProtocol{}
	if err := env.srv.k8sClient.Get(ctx, ctrlKey(testProtocolName), proto); err != nil {
		t.Fatalf("get protocol: %v", err)
	}
	proto.Spec.Protocol.NVMeOFTCP.HdrDigest = true
	proto.Spec.Protocol.NVMeOFTCP.DataDigest = true
	if err := env.srv.k8sClient.Update(ctx, proto); err != nil {
		t.Fatalf("update protocol: %v", err)
	}

	resp, err := env.srv.CreateVolume(ctx, baseCreateVolumeRequest())
	if err != nil {
		t.Fatalf("CreateVolume: %v", err)
	}
	if got := digestKeys(resp.GetVolume().GetVolumeContext()); len(got) != 0 {
		t.Errorf("VolumeContext digest keys = %v, want none", got)
	}
	pvs, _, err := env.srv.loadPillarVolumeState(ctx, pillarVolumeStateNameFromVolumeID(resp.GetVolume().GetVolumeId()))
	if err != nil {
		t.Fatalf("load PillarVolumeState: %v", err)
	}
	n := pvs.Spec.Resolved.Protocol.NVMeOFTCP
	if n == nil || n.HdrDigest || n.DataDigest {
		t.Errorf("resolved nvmeofTcp = %+v, want digests cleared", n)
	}
}
