/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package csi

import (
	"bufio"
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/google/uuid"
)

// hostNQNFile is the standard path where the Linux NVMe driver stores the
// host NQN assigned to this machine.  It is written by nvme-cli on first
// boot (or by the OS vendor) and is stable across reboots.
const hostNQNFile = "/etc/nvme/hostnqn"

// hostIDFile is the companion path holding the NVMe host ID UUID; nvme-cli
// reads it as the `hostid=` option for every fabrics connect.  We persist
// it next to the host NQN so both identities survive pod restarts and stay
// visible to external nvme-cli tooling.
const hostIDFile = "/etc/nvme/hostid"

// hostNQNUUIDPrefix is the NVMe-spec-mandated prefix for UUID-form host NQNs
// generated by initiators that do not have a vendor-assigned identity.
// See NVMe-oF 1.1 §4.5 and `nvme show-hostnqn`.
const hostNQNUUIDPrefix = "nqn.2014-08.org.nvmexpress:uuid:"

// ReadHostNQN reads the NVMe host NQN for this node from the well-known
// system file (/etc/nvme/hostnqn), generating and persisting a spec-form
// UUID NQN when the file is absent or empty.
//
// Generation matches `nvme show-hostnqn` semantics so that pillar-csi works
// out-of-the-box on hosts where nvme-cli is not preinstalled (the common
// case in containerized environments such as Kind / CI runners).  The
// generated file is written to the hostPath-mounted /etc/nvme directory and
// thus persists across pod restarts and is observable by external tooling
// such as nvme-cli.
func ReadHostNQN() (string, error) {
	return readOrGenerateHostNQN(hostNQNFile)
}

// ReadHostID reads the NVMe host ID (a bare UUID, not an NQN) from
// /etc/nvme/hostid, generating and persisting one on first call when the
// file is absent or empty.  The kernel /dev/nvme-fabrics interface accepts
// `hostid=<uuid>` and recent Linux releases require it whenever `hostnqn=`
// is also set; supplying both keeps pillar-node compatible with strict
// kernels and matches what nvme-cli always sends.
func ReadHostID() (string, error) {
	return readOrGenerateHostID(hostIDFile)
}

// readOrGenerateHostNQN is the testable inner implementation.  When path is
// missing or empty it creates the parent directory (mode 0o755), writes a
// freshly-generated UUID NQN with mode 0o644, and returns it.  Mode 0o644
// matches the default written by `nvme show-hostnqn -G` so the file is
// readable by every container that hostPath-mounts /etc/nvme.
func readOrGenerateHostNQN(path string) (string, error) {
	data, err := os.ReadFile(path) //nolint:gosec
	if err == nil {
		nqn := strings.TrimSpace(string(data))
		if nqn != "" {
			return nqn, nil
		}
	} else if !os.IsNotExist(err) {
		return "", fmt.Errorf("read host NQN from %s: %w", path, err)
	}

	nqn := hostNQNUUIDPrefix + uuid.NewString()
	mkErr := os.MkdirAll(filepath.Dir(path), 0o750) // #nosec G703 -- operator-configured host identity file
	if mkErr != nil {
		return "", fmt.Errorf("create host NQN directory %s: %w", filepath.Dir(path), mkErr)
	}
	// 0o644 matches `nvme show-hostnqn -G` so the file is readable by any
	// non-root container that hostPath-mounts /etc/nvme.
	writeErr := os.WriteFile(path, []byte(nqn+"\n"), 0o644) //nolint:gosec // see comment above
	if writeErr != nil {
		return "", fmt.Errorf("persist generated host NQN to %s: %w", path, writeErr)
	}
	return nqn, nil
}

// readOrGenerateHostID is the testable inner implementation of ReadHostID.
// File semantics mirror readOrGenerateHostNQN (same parent dir, same mode,
// same atomic create-or-read contract); the only difference is the payload
// is a bare UUID string rather than a UUID-form NQN.
func readOrGenerateHostID(path string) (string, error) {
	data, err := os.ReadFile(path) //nolint:gosec
	if err == nil {
		id := strings.TrimSpace(string(data))
		if id != "" {
			return id, nil
		}
	} else if !os.IsNotExist(err) {
		return "", fmt.Errorf("read host ID from %s: %w", path, err)
	}

	id := uuid.NewString()
	mkErr := os.MkdirAll(filepath.Dir(path), 0o750) // #nosec G703 -- operator-configured host identity file
	if mkErr != nil {
		return "", fmt.Errorf("create host ID directory %s: %w", filepath.Dir(path), mkErr)
	}
	writeErr := os.WriteFile(path, []byte(id+"\n"), 0o644) //nolint:gosec // matches nvme-cli default
	if writeErr != nil {
		return "", fmt.Errorf("persist generated host ID to %s: %w", path, writeErr)
	}
	return id, nil
}

// DefaultISCSIInitiatorNameFile is the open-iscsi location of the node's
// initiator IQN.  The pillar-node process reads (and on first start, writes) it through
// the /etc/iscsi hostPath so the identity survives pod restarts and matches
// what host tooling would use.
const DefaultISCSIInitiatorNameFile = "/etc/iscsi/initiatorname.iscsi"

// generatedInitiatorIQNPrefix prefixes IQNs generated by ReadInitiatorIQN;
// a 32-hex-digit random suffix follows.
const generatedInitiatorIQNPrefix = "iqn.2026-01.com.bhyoo.pillar-csi:node."

// initiatorNameKey is the open-iscsi key of the initiator IQN line.
const initiatorNameKey = "InitiatorName="

// maxISCSINameLen is the RFC 3720 §3.2.6.1 limit on iSCSI names (bytes).
const maxISCSINameLen = 223

// iscsiNamePattern accepts the three RFC 3720/3980 iSCSI name formats:
// iqn.<yyyy-mm>.<reversed domain>[:<unique>], eui.<16 hex> and
// naa.<16 or 32 hex>.
var iscsiNamePattern = regexp.MustCompile(
	`^(?i:iqn\.[0-9]{4}-[0-9]{2}\.[a-z0-9]([a-z0-9.-]*[a-z0-9])?(:[a-z0-9.:_-]+)?` +
		`|eui\.[0-9a-f]{16}|naa\.([0-9a-f]{16}|[0-9a-f]{32}))$`)

// ReadInitiatorIQN returns the iSCSI initiator IQN of this node from the
// open-iscsi style file at path (normally DefaultISCSIInitiatorNameFile).
//
// The first "InitiatorName=<iqn>" line wins; blank lines and '#' comments are
// ignored and surrounding whitespace is trimmed.  When the file is absent or
// holds no non-empty InitiatorName, a fresh
// "iqn.2026-01.com.bhyoo.pillar-csi:node.<32 hex>" is generated and persisted
// as "InitiatorName=<iqn>\n" (mode 0o644, parent directory created).  An
// existing name that is not a valid iSCSI name is an error; it is never
// overwritten.
func ReadInitiatorIQN(path string) (string, error) {
	data, err := os.ReadFile(path) //nolint:gosec // G304: operator-supplied identity file
	if err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("read iSCSI initiator name from %s: %w", path, err)
	}
	if err == nil {
		iqn, found := parseInitiatorName(data)
		if found {
			if !validISCSIName(iqn) {
				return "", fmt.Errorf("read iSCSI initiator name from %s: %q is not a valid iSCSI name "+
					"(want iqn.yyyy-mm.<domain>[:<id>], eui.<16 hex> or naa.<hex>)", path, iqn)
			}
			return iqn, nil
		}
	}

	suffix := make([]byte, 16)
	_, randErr := rand.Read(suffix)
	if randErr != nil {
		return "", fmt.Errorf("generate iSCSI initiator name for %s: %w", path, randErr)
	}
	iqn := generatedInitiatorIQNPrefix + hex.EncodeToString(suffix)
	mkErr := os.MkdirAll(filepath.Dir(path), 0o750) // #nosec G703 -- operator-configured identity file
	if mkErr != nil {
		return "", fmt.Errorf("create iSCSI initiator name directory %s: %w", filepath.Dir(path), mkErr)
	}
	// 0o644 matches the open-iscsi default so host tooling can read it.
	writeErr := os.WriteFile(path, []byte(initiatorNameKey+iqn+"\n"), 0o644) //nolint:gosec // see comment above
	if writeErr != nil {
		return "", fmt.Errorf("persist generated iSCSI initiator name to %s: %w", path, writeErr)
	}
	// WriteFile keeps the mode of a pre-existing file (one without a name)
	// and is subject to the umask, so set the mode explicitly.
	chmodErr := os.Chmod(path, 0o644) //nolint:gosec // readable by host tooling, see above
	if chmodErr != nil {
		return "", fmt.Errorf("chmod generated iSCSI initiator name file %s: %w", path, chmodErr)
	}
	return iqn, nil
}

// parseInitiatorName returns the value of the first non-empty InitiatorName
// line of an open-iscsi initiatorname file.
func parseInitiatorName(data []byte) (string, bool) {
	sc := bufio.NewScanner(bytes.NewReader(data))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		value, ok := strings.CutPrefix(line, initiatorNameKey)
		if !ok {
			continue
		}
		value = strings.TrimSpace(value)
		if value != "" {
			return value, true
		}
	}
	return "", false
}

// validISCSIName reports whether name is a well-formed iSCSI name.
func validISCSIName(name string) bool {
	return len(name) <= maxISCSINameLen && iscsiNamePattern.MatchString(name)
}
