/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package csi

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/google/uuid"
)

// hostNQNFile is the standard path where the Linux NVMe driver stores the
// host NQN assigned to this machine.  It is written by nvme-cli on first
// boot (or by the OS vendor) and is stable across reboots.
const hostNQNFile = "/etc/nvme/hostnqn"

// hostNQNUUIDPrefix is the NVMe-spec-mandated prefix for UUID-form host NQNs
// generated by initiators that do not have a vendor-assigned identity.
// See NVMe-oF 1.1 §4.5 and `nvme show-hostnqn`.
const hostNQNUUIDPrefix = "nqn.2014-08.org.nvmexpress:uuid:"

// ReadHostNQN reads the NVMe host NQN for this node from the well-known
// system file (/etc/nvme/hostnqn), generating and persisting a spec-form
// UUID NQN when the file is absent or empty.
//
// Generation matches `nvme show-hostnqn` semantics so that pillar-csi works
// out-of-the-box on hosts where nvme-cli is not preinstalled (the common
// case in containerized environments such as Kind / CI runners).  The
// generated file is written to the hostPath-mounted /etc/nvme directory and
// thus persists across pod restarts and is observable by external tooling
// such as nvme-cli.
func ReadHostNQN() (string, error) {
	return readOrGenerateHostNQN(hostNQNFile)
}

// readOrGenerateHostNQN is the testable inner implementation.  When path is
// missing or empty it creates the parent directory (mode 0o755), writes a
// freshly-generated UUID NQN with mode 0o644, and returns it.  Mode 0o644
// matches the default written by `nvme show-hostnqn -G` so the file is
// readable by every container that hostPath-mounts /etc/nvme.
func readOrGenerateHostNQN(path string) (string, error) {
	data, err := os.ReadFile(path) //nolint:gosec
	if err == nil {
		nqn := strings.TrimSpace(string(data))
		if nqn != "" {
			return nqn, nil
		}
	} else if !os.IsNotExist(err) {
		return "", fmt.Errorf("read host NQN from %s: %w", path, err)
	}

	nqn := hostNQNUUIDPrefix + uuid.NewString()
	mkErr := os.MkdirAll(filepath.Dir(path), 0o750)
	if mkErr != nil {
		return "", fmt.Errorf("create host NQN directory %s: %w", filepath.Dir(path), mkErr)
	}
	// 0o644 matches `nvme show-hostnqn -G` so the file is readable by any
	// non-root container that hostPath-mounts /etc/nvme.
	writeErr := os.WriteFile(path, []byte(nqn+"\n"), 0o644) //nolint:gosec // see comment above
	if writeErr != nil {
		return "", fmt.Errorf("persist generated host NQN to %s: %w", path, writeErr)
	}
	return nqn, nil
}
