/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package csi

// Resolve.go — the single effective-configuration resolution point.
//
// CreateVolume resolves the configuration of a new volume from live CRs:
//
//	PillarStore.spec.backend / PillarProtocol.spec.protocol   (infrastructure)
//	  ↓ PillarStorageClass.spec.overrides + spec.filesystem   (binding)
//	  ↓ StorageClass parameter documents                      (hand-written classes only)
//	  ↓ PVC annotation documents                              (per volume)
//
// A StorageClass generated by a PillarStorageClass carries only its identity
// (pillar-csi.bhyoo.com/storage-class) plus csi.storage.k8s.io/fstype; a
// hand-written StorageClass names the PillarStore and PillarProtocol
// (pillar-csi.bhyoo.com/store-ref, protocol-ref) and may carry the same three
// documents a PVC can.  The result is persisted in
// PillarVolumeState.spec.resolved so retries and restores are stable.

import (
	"context"
	"fmt"
	"maps"
	"strconv"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	corev1 "k8s.io/api/core/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	v1alpha1 "github.com/isac322/pillar-csi/api/v1alpha1"
	"github.com/isac322/pillar-csi/internal/configdocs"
)

// StorageClass parameter keys.
const (
	// ParamBinding names the PillarStorageClass that generated the
	// StorageClass (identity ref of a generated class).
	paramBinding = "pillar-csi.bhyoo.com/storage-class"

	// ParamStoreRef names the PillarStore of a hand-written StorageClass.
	paramStoreRef = "pillar-csi.bhyoo.com/store-ref"

	// ParamProtocolRef names the PillarProtocol of a hand-written StorageClass.
	paramProtocolRef = "pillar-csi.bhyoo.com/protocol-ref"

	// ParamBackendDoc, paramProtocolDoc and paramFilesystemDoc are the
	// configuration documents a hand-written StorageClass may carry; the
	// keys and shapes are identical to the PVC annotations.
	paramBackendDoc    = configdocs.BackendDocKey
	paramProtocolDoc   = configdocs.ProtocolDocKey
	paramFilesystemDoc = configdocs.FilesystemDocKey

	// ParamFSTypeSC is the Kubernetes StorageClass fsType parameter; the
	// external-provisioner copies it into the PV's spec.csi.fsType.
	paramFSTypeSC = "csi.storage.k8s.io/fstype"
)

// VolumeContext keys carrying the resolved node-side settings from
// CreateVolume to NodeStageVolume / NodePublishVolume.
const (
	// ParamNVMeOFMaxQueueSize is the fabrics queue_size connect option
	// (resolved nvmeofTcp.maxQueueSize).
	paramNVMeOFMaxQueueSize = "pillar-csi.bhyoo.com/nvmeof-max-queue-size"

	// ParamNVMeOFCtrlLossTmo is the ctrl_loss_tmo connect option in seconds
	// (resolved nvmeofTcp.ctrlLossTmo).
	paramNVMeOFCtrlLossTmo = "pillar-csi.bhyoo.com/nvmeof-ctrl-loss-tmo"

	// ParamNVMeOFReconnectDelay is the reconnect_delay connect option in
	// seconds (resolved nvmeofTcp.reconnectDelay).
	paramNVMeOFReconnectDelay = "pillar-csi.bhyoo.com/nvmeof-reconnect-delay"

	// ParamFSType is the resolved filesystem type (ext4 or xfs);
	// NodeStageVolume formats and mounts with it in place of the PV's
	// csi.fsType.
	paramFSType = "pillar-csi.bhyoo.com/fs-type"

	// ParamMkfsOptions is the resolved mkfs argument list, a JSON string
	// array, used when NodeStageVolume formats a blank device.
	paramMkfsOptions = "pillar-csi.bhyoo.com/mkfs-options"

	// ParamMountOptions is the resolved mount option list, a JSON string
	// array; when present it replaces the capability's mount flags (the
	// StorageClass mountOptions).
	paramMountOptions = "pillar-csi.bhyoo.com/mount-options"
)

// generatedClassParams are the pillar-csi keys a generated StorageClass may
// carry; handWrittenClassParams those of a hand-written one.
var (
	generatedClassParams = map[string]bool{paramBinding: true}

	handWrittenClassParams = map[string]bool{
		paramStoreRef:      true,
		paramProtocolRef:   true,
		paramBackendDoc:    true,
		paramProtocolDoc:   true,
		paramFilesystemDoc: true,
	}
)

// invalidConfig returns an InvalidArgument status for a configuration error.
func invalidConfig(format string, args ...any) error {
	return status.Errorf(codes.InvalidArgument, format, args...)
}

// classLayer is the StorageClass-level configuration: the referenced CRs and
// the class documents (binding overrides for a generated class, parameter
// documents for a hand-written one).
type classLayer struct {
	store    *v1alpha1.PillarStore
	protocol *v1alpha1.PillarProtocol

	backend    *v1alpha1.BackendOverrides
	protocolOv *v1alpha1.ProtocolOverrides

	// filesystem is the class filesystem document (binding
	// spec.filesystem, or a hand-written class's filesystem parameter).
	filesystem *v1alpha1.FilesystemConfig

	// source names the class layer in error messages.
	source string
}

// resolution is the outcome of resolveVolumeConfig.
type resolution struct {
	// resolved is the effective configuration.
	resolved *v1alpha1.ResolvedVolumeConfig

	// agentRef is the PillarAgent that hosts the store.
	agentRef string

	// pvcFS is the claim's filesystem document (nil when the claim sets
	// none); CreateVolume rejects it for a raw block volume.
	pvcFS *v1alpha1.FilesystemConfig
}

// resolveVolumeConfig resolves the effective configuration of a new volume
// from the StorageClass parameters, the CRs they reference and the claim's
// annotations.  Errors are gRPC status errors: InvalidArgument for a bad
// parameter or document, FailedPrecondition for a referenced CR (or claim)
// that does not exist, Internal otherwise.
//
// When recorded is non-nil (a retry of a lifecycle whose first attempt
// already recorded its resolution) only the export settings are resolved
// from the live CRs: the backend and filesystem come from recorded, so a
// later store or filesystem change can neither block nor alter the retry of
// a volume whose backend already exists.
func (s *ControllerServer) resolveVolumeConfig(
	ctx context.Context,
	scParams map[string]string,
	recorded *v1alpha1.ResolvedVolumeConfig,
) (*resolution, error) {
	class, err := s.resolveClassLayer(ctx, scParams, recorded == nil)
	if err != nil {
		return nil, err
	}
	pvc, err := s.claimDocs(ctx, scParams)
	if err != nil {
		return nil, err
	}

	protocol, err := resolveProtocol(class, pvc)
	if err != nil {
		return nil, err
	}
	if recorded != nil {
		if protocol.Kind() != recorded.Protocol.Kind() {
			return nil, status.Errorf(codes.FailedPrecondition,
				"PillarProtocol %q now configures %q but the volume was provisioned over %q",
				class.protocol.Name, protocol.Kind(), recorded.Protocol.Kind())
		}
		exportOnly := recorded.DeepCopy()
		exportOnly.Protocol = protocol
		return &resolution{resolved: exportOnly, pvcFS: pvc.Filesystem}, nil
	}

	backend := *class.store.Spec.Backend.DeepCopy()
	for _, layer := range []struct {
		source string
		ov     *v1alpha1.BackendOverrides
	}{
		{class.source, class.backend},
		{configdocs.BackendDocKey + " (PVC annotation)", pvc.Backend},
	} {
		err = applyBackendOverride(&backend, layer.ov, layer.source)
		if err != nil {
			return nil, invalidConfig("%v", err)
		}
	}
	if lvm := backend.LVM; lvm != nil && lvm.ProvisioningMode == "" {
		// The single LVM default (the CRD default), applied on every path.
		lvm.ProvisioningMode = v1alpha1.LVMProvisioningModeLinear
	}
	if lvm := backend.LVM; lvm != nil &&
		lvm.ProvisioningMode == v1alpha1.LVMProvisioningModeThin && lvm.ThinPool == "" {
		return nil, invalidConfig(
			"lvm.provisioningMode thin requires PillarStore %q to set lvm.thinPool", class.store.Name)
	}

	fs, err := resolveFilesystem(scParams, class.filesystem, pvc.Filesystem)
	if err != nil {
		return nil, err
	}

	return &resolution{
		resolved: &v1alpha1.ResolvedVolumeConfig{
			Backend:    backend,
			Protocol:   protocol,
			Filesystem: fs,
		},
		agentRef: class.store.Spec.AgentRef,
		pvcFS:    pvc.Filesystem,
	}, nil
}

// resolveProtocol applies the class and claim protocol overrides to the
// referenced PillarProtocol's configuration.
func resolveProtocol(class *classLayer, pvc pvcDocs) (v1alpha1.ProtocolSpec, error) {
	protocol := *class.protocol.Spec.Protocol.DeepCopy()
	for _, layer := range []struct {
		source string
		ov     *v1alpha1.ProtocolOverrides
	}{
		{class.source, class.protocolOv},
		{configdocs.ProtocolDocKey + " (PVC annotation)", pvc.Protocol},
	} {
		err := applyProtocolOverride(&protocol, layer.ov, layer.source)
		if err != nil {
			return v1alpha1.ProtocolSpec{}, invalidConfig("%v", err)
		}
	}
	return protocol, nil
}

// resolveClassLayer reads the StorageClass identity parameters and loads the
// CRs and class documents they name.  The PillarStore is loaded only when
// withStore is true (a first attempt); a retry reuses the recorded backend.
func (s *ControllerServer) resolveClassLayer(
	ctx context.Context,
	scParams map[string]string,
	withStore bool,
) (*classLayer, error) {
	bindingName := scParams[paramBinding]
	if bindingName != "" {
		err := rejectUnknownPillarKeys("StorageClass parameter", scParams, generatedClassParams)
		if err != nil {
			return nil, invalidConfig("%v (a class generated by PillarStorageClass %q carries only %s)",
				err, bindingName, paramBinding)
		}
		binding := &v1alpha1.PillarStorageClass{}
		err = s.getCR(ctx, bindingName, binding, "PillarStorageClass", paramBinding)
		if err != nil {
			return nil, err
		}
		class := &classLayer{
			filesystem: binding.Spec.Filesystem,
			source:     fmt.Sprintf("PillarStorageClass %q spec.overrides", bindingName),
		}
		if ov := binding.Spec.Overrides; ov != nil {
			class.backend, class.protocolOv = ov.Backend, ov.Protocol
		}
		err = s.loadStoreAndProtocol(ctx, class, binding.Spec.StoreRef, binding.Spec.ProtocolRef, withStore)
		if err != nil {
			return nil, err
		}
		return class, nil
	}

	err := rejectUnknownPillarKeys("StorageClass parameter", scParams, handWrittenClassParams)
	if err != nil {
		return nil, invalidConfig("%v", err)
	}
	storeName, protocolName := scParams[paramStoreRef], scParams[paramProtocolRef]
	if storeName == "" || protocolName == "" {
		return nil, invalidConfig(
			"StorageClass parameters must name the configuration: either %q (generated by a "+
				"PillarStorageClass) or both %q and %q",
			paramBinding, paramStoreRef, paramProtocolRef)
	}

	class := &classLayer{source: "StorageClass parameter"}
	backendDoc, err := configdocs.DecodeBackendOverride(
		paramBackendDoc+" (StorageClass parameter)", scParams[paramBackendDoc])
	if err != nil {
		return nil, invalidConfig("%v", err)
	}
	protocolDoc, err := configdocs.DecodeProtocolOverride(
		paramProtocolDoc+" (StorageClass parameter)", scParams[paramProtocolDoc])
	if err != nil {
		return nil, invalidConfig("%v", err)
	}
	filesystemDoc, err := configdocs.DecodeFilesystemDoc(
		paramFilesystemDoc+" (StorageClass parameter)", scParams[paramFilesystemDoc])
	if err != nil {
		return nil, invalidConfig("%v", err)
	}
	class.backend, class.protocolOv, class.filesystem = backendDoc, protocolDoc, filesystemDoc
	err = s.loadStoreAndProtocol(ctx, class, storeName, protocolName, withStore)
	if err != nil {
		return nil, err
	}
	return class, nil
}

// loadStoreAndProtocol fetches the named PillarProtocol and, when withStore
// is true, the named PillarStore and checks the pair is compatible.
func (s *ControllerServer) loadStoreAndProtocol(
	ctx context.Context,
	class *classLayer,
	storeName, protocolName string,
	withStore bool,
) error {
	class.protocol = &v1alpha1.PillarProtocol{}
	err := s.getCR(ctx, protocolName, class.protocol, "PillarProtocol", paramProtocolRef)
	if err != nil {
		return err
	}
	if class.protocol.Spec.Protocol.Kind() == "" {
		return invalidConfig("PillarProtocol %q: spec.protocol sets no protocol member", protocolName)
	}
	if !withStore {
		return nil
	}
	class.store = &v1alpha1.PillarStore{}
	err = s.getCR(ctx, storeName, class.store, "PillarStore", paramStoreRef)
	if err != nil {
		return err
	}
	if class.store.Spec.Backend.Kind() == "" {
		return invalidConfig("PillarStore %q: spec.backend sets no backend member", storeName)
	}
	compat := v1alpha1.Compatible(class.store.Spec.Backend, class.protocol.Spec.Protocol)
	if !compat.OK {
		return invalidConfig("PillarStore %q / PillarProtocol %q: %s", storeName, protocolName, compat.Message)
	}
	return nil
}

// getCR reads a cluster-scoped CR by name.  A missing CR is
// FailedPrecondition (the provisioner retries once it exists).
func (s *ControllerServer) getCR(ctx context.Context, name string, obj client.Object, kind, via string) error {
	err := s.k8sClient.Get(ctx, types.NamespacedName{Name: name}, obj)
	if err == nil {
		return nil
	}
	if k8serrors.IsNotFound(err) {
		return status.Errorf(codes.FailedPrecondition, "%s %q (named via %s) not found", kind, name, via)
	}
	return status.Errorf(codes.Internal, "get %s %q: %v", kind, name, err)
}

// claimDocs decodes the configuration documents of the claim identified by
// the external-provisioner's --extra-create-metadata parameters.  Without
// that metadata no claim is known and the layer is empty; a claim that is
// named but cannot be read is an error, because provisioning without it
// would silently drop the claim's settings.
func (s *ControllerServer) claimDocs(ctx context.Context, scParams map[string]string) (pvcDocs, error) {
	pvcName, pvcNamespace := scParams[paramPVCNameMeta], scParams[paramPVCNamespaceMeta]
	if pvcName == "" || pvcNamespace == "" {
		return pvcDocs{}, nil
	}
	pvc := &corev1.PersistentVolumeClaim{}
	err := s.apiReader.Get(ctx, types.NamespacedName{Namespace: pvcNamespace, Name: pvcName}, pvc)
	if err != nil {
		if k8serrors.IsNotFound(err) {
			return pvcDocs{}, status.Errorf(codes.FailedPrecondition,
				"PersistentVolumeClaim %s/%s not found", pvcNamespace, pvcName)
		}
		return pvcDocs{}, status.Errorf(codes.Internal,
			"get PersistentVolumeClaim %s/%s: %v", pvcNamespace, pvcName, err)
	}
	docs, err := decodePVCAnnotations(pvc.Annotations)
	if err != nil {
		return pvcDocs{}, invalidConfig("PVC %s/%s annotation validation failed: %v", pvcNamespace, pvcName, err)
	}
	return docs, nil
}

// applyBackendOverride applies an override document onto the effective
// backend.  The override member must match the backend member.
func applyBackendOverride(backend *v1alpha1.BackendSpec, ov *v1alpha1.BackendOverrides, source string) error {
	if ov == nil {
		return nil
	}
	switch {
	case ov.ZFS != nil:
		if backend.ZFS == nil {
			return fmt.Errorf("%s: zfs overrides do not apply to a %s backend", source, backend.Kind())
		}
		if len(ov.ZFS.Properties) > 0 {
			props := make(map[string]string, len(backend.ZFS.Properties)+len(ov.ZFS.Properties))
			maps.Copy(props, backend.ZFS.Properties)
			maps.Copy(props, ov.ZFS.Properties)
			backend.ZFS.Properties = props
		}
	case ov.LVM != nil:
		if backend.LVM == nil {
			return fmt.Errorf("%s: lvm overrides do not apply to a %s backend", source, backend.Kind())
		}
		if ov.LVM.ProvisioningMode != "" {
			backend.LVM.ProvisioningMode = ov.LVM.ProvisioningMode
		}
	}
	return nil
}

// applyProtocolOverride applies an override document onto the effective
// protocol.  The override member must match the protocol member.
func applyProtocolOverride(protocol *v1alpha1.ProtocolSpec, ov *v1alpha1.ProtocolOverrides, source string) error {
	if ov == nil || ov.NVMeOFTCP == nil {
		return nil
	}
	if protocol.NVMeOFTCP == nil {
		return fmt.Errorf("%s: nvmeofTcp overrides do not apply to a %s protocol", source, protocol.Kind())
	}
	dst, src := protocol.NVMeOFTCP, ov.NVMeOFTCP
	for _, f := range []struct {
		dst **int32
		src *int32
	}{
		{&dst.MaxQueueSize, src.MaxQueueSize},
		{&dst.InCapsuleDataSize, src.InCapsuleDataSize},
		{&dst.CtrlLossTmo, src.CtrlLossTmo},
		{&dst.ReconnectDelay, src.ReconnectDelay},
	} {
		if f.src != nil {
			v := *f.src
			*f.dst = &v
		}
	}
	return nil
}

// resolveFilesystem layers the filesystem documents: ext4 default, the
// class document (with a hand-written class's csi.storage.k8s.io/fstype),
// then the PVC document.  Lists follow list semantics: nil inherits, an
// explicit empty list clears.
func resolveFilesystem(
	scParams map[string]string,
	classFS, pvcFS *v1alpha1.FilesystemConfig,
) (*v1alpha1.FilesystemConfig, error) {
	fs, err := classFilesystemBase(scParams, classFS)
	if err != nil {
		return nil, err
	}
	for _, layer := range []*v1alpha1.FilesystemConfig{classFS, pvcFS} {
		if layer == nil {
			continue
		}
		if layer.FSType != "" {
			fs.FSType = layer.FSType
		}
		if layer.MkfsOptions != nil {
			fs.MkfsOptions = copyList(layer.MkfsOptions)
		}
		if layer.MountOptions != nil {
			fs.MountOptions = copyList(layer.MountOptions)
		}
	}
	return fs, nil
}

// classFilesystemBase is the filesystem configuration below the class
// document: the ext4 default and, for a hand-written class, its
// csi.storage.k8s.io/fstype.  A generated class's fstype and mountOptions
// are only copies of the live binding's spec.filesystem (and may be stale),
// so a generated class starts from ext4 and an explicit empty mount list,
// which keeps a stale copy from reaching the node through the capability.
func classFilesystemBase(
	scParams map[string]string,
	classFS *v1alpha1.FilesystemConfig,
) (*v1alpha1.FilesystemConfig, error) {
	fs := &v1alpha1.FilesystemConfig{FSType: defaultFsType}
	if scParams[paramBinding] != "" {
		fs.MountOptions = &[]string{}
		return fs, nil
	}
	scFSType := scParams[paramFSTypeSC]
	if scFSType == "" {
		return fs, nil
	}
	if scFSType != defaultFsType && scFSType != xfsFsType {
		return nil, invalidConfig("unsupported StorageClass parameter %s %q: must be %q or %q",
			paramFSTypeSC, scFSType, defaultFsType, xfsFsType)
	}
	if classFS != nil && classFS.FSType != "" && classFS.FSType != scFSType {
		return nil, invalidConfig("StorageClass parameter %s fsType %q conflicts with %s %q",
			paramFilesystemDoc, classFS.FSType, paramFSTypeSC, scFSType)
	}
	fs.FSType = scFSType
	return fs, nil
}

func copyList(p *[]string) *[]string {
	out := append([]string{}, (*p)...)
	return &out
}

// nodeVolumeContext returns the VolumeContext entries derived from the
// resolved configuration that the node needs at stage time: NVMe-oF connect
// tuning and the filesystem settings.
func nodeVolumeContext(resolved *v1alpha1.ResolvedVolumeConfig, volCtx map[string]string) {
	if resolved == nil {
		return
	}
	if n := resolved.Protocol.NVMeOFTCP; n != nil {
		for _, f := range []struct {
			key string
			v   *int32
		}{
			{paramNVMeOFCtrlLossTmo, n.CtrlLossTmo},
			{paramNVMeOFReconnectDelay, n.ReconnectDelay},
			{paramNVMeOFMaxQueueSize, n.MaxQueueSize},
		} {
			if f.v != nil {
				volCtx[f.key] = strconv.FormatInt(int64(*f.v), 10)
			}
		}
	}
	filesystemVolumeContext(resolved.Filesystem, volCtx)
}
