/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package csi

// Resolve.go — the single effective-configuration resolution point.
//
// CreateVolume resolves the configuration of a new volume from live CRs:
//
//	PillarStore.spec.backend / PillarProtocol.spec.protocol   (infrastructure)
//	  ↓ PillarStorageClass.spec.overrides + spec.filesystem   (binding)
//	  ↓ StorageClass parameter documents                      (hand-written classes only)
//	  ↓ PVC annotation documents                              (per volume)
//
// A StorageClass generated by a PillarStorageClass carries only its identity
// (pillar-csi.bhyoo.com/storage-class) plus csi.storage.k8s.io/fstype; a
// hand-written StorageClass names the PillarStore and PillarProtocol
// (pillar-csi.bhyoo.com/store-ref, protocol-ref) and may carry the same three
// documents a PVC can.  The result is persisted in
// PillarVolumeState.spec.resolved so retries and restores are stable.

import (
	"context"
	"fmt"
	"maps"
	"strconv"

	csi "github.com/container-storage-interface/spec/lib/go/csi"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	corev1 "k8s.io/api/core/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	v1alpha1 "github.com/isac322/pillar-csi/api/v1alpha1"
	"github.com/isac322/pillar-csi/internal/configdocs"
)

// StorageClass parameter keys.
const (
	// ParamBinding names the PillarStorageClass that generated the
	// StorageClass (identity ref of a generated class).
	paramBinding = "pillar-csi.bhyoo.com/storage-class"

	// ParamStoreRef names the PillarStore of a hand-written StorageClass.
	paramStoreRef = "pillar-csi.bhyoo.com/store-ref"

	// ParamProtocolRef names the PillarProtocol of a hand-written StorageClass.
	paramProtocolRef = "pillar-csi.bhyoo.com/protocol-ref"

	// ParamBackendDoc, paramProtocolDoc and paramFilesystemDoc are the
	// configuration documents a hand-written StorageClass may carry; the
	// keys and shapes are identical to the PVC annotations.
	paramBackendDoc    = configdocs.BackendDocKey
	paramProtocolDoc   = configdocs.ProtocolDocKey
	paramFilesystemDoc = configdocs.FilesystemDocKey

	// ParamFSTypeSC is the Kubernetes StorageClass fsType parameter; the
	// external-provisioner copies it into the PV's spec.csi.fsType.
	paramFSTypeSC = "csi.storage.k8s.io/fstype"

	// ParamLocalAttach enables local attach on a hand-written StorageClass
	// ("true" or "false"; absent is false).  A generated class carries the
	// setting in its PillarStorageClass spec.localAttach instead.
	paramLocalAttach = "pillar-csi.bhyoo.com/local-attach"
)

// VolumeContext keys carrying the resolved node-side settings from
// CreateVolume to NodeStageVolume / NodePublishVolume.
const (
	// ParamNVMeOFMaxQueueSize is the fabrics queue_size connect option
	// (resolved nvmeofTcp.maxQueueSize).
	paramNVMeOFMaxQueueSize = "pillar-csi.bhyoo.com/nvmeof-max-queue-size"

	// ParamNVMeOFCtrlLossTmo is the ctrl_loss_tmo connect option in seconds
	// (resolved nvmeofTcp.ctrlLossTmo).
	paramNVMeOFCtrlLossTmo = "pillar-csi.bhyoo.com/nvmeof-ctrl-loss-tmo"

	// ParamNVMeOFReconnectDelay is the reconnect_delay connect option in
	// seconds (resolved nvmeofTcp.reconnectDelay).
	paramNVMeOFReconnectDelay = "pillar-csi.bhyoo.com/nvmeof-reconnect-delay"

	// ParamNVMeOFMaxDataTransferSize is the resolved
	// nvmeofTcp.maxDataTransferSize in bytes (0 = no limit).  When the
	// target advertises no limit (MDTS 0) the node caps the namespace's
	// queue/max_sectors_kb to it; a volume provisioned before the key
	// existed is treated as v1alpha1.DefaultMaxDataTransferSize.
	paramNVMeOFMaxDataTransferSize = "pillar-csi.bhyoo.com/nvmeof-max-data-transfer-size"

	// ParamFSType is the resolved filesystem type.  NFS volumes carry
	// "nfs" here so the node dispatches to the file-protocol handler.
	paramFSType = "pillar-csi.bhyoo.com/fs-type"

	// ParamNFSVersion is the resolved NFS protocol version used by the node
	// mount helper.  It is persisted in VolumeContext with the other resolved
	// settings so retries do not follow a changed PillarProtocol.
	paramNFSVersion = "pillar-csi.bhyoo.com/nfs-version"

	// ParamMkfsOptions is the resolved mkfs argument list, a JSON string
	// array, used when NodeStageVolume formats a blank device.
	paramMkfsOptions = "pillar-csi.bhyoo.com/mkfs-options"

	// ParamMountOptions is the resolved mount option list, a JSON string
	// array; when present it replaces the capability's mount flags (the
	// StorageClass mountOptions).
	paramMountOptions = "pillar-csi.bhyoo.com/mount-options"

	// ParamPeriodicTrim is the resolved periodicTrim setting ("true" or
	// "false"), present only when a layer sets it; "false" opts the
	// staged filesystem out of the node's periodic trim.
	paramPeriodicTrim = "pillar-csi.bhyoo.com/periodic-trim"
)

// generatedClassParams are the pillar-csi keys a generated StorageClass may
// carry; handWrittenClassParams those of a hand-written one.
var (
	generatedClassParams = map[string]bool{paramBinding: true}

	handWrittenClassParams = map[string]bool{
		paramStoreRef:      true,
		paramProtocolRef:   true,
		paramBackendDoc:    true,
		paramProtocolDoc:   true,
		paramFilesystemDoc: true,
		paramLocalAttach:   true,
	}
)

// invalidConfig returns an InvalidArgument status for a configuration error.
func invalidConfig(format string, args ...any) error {
	return status.Errorf(codes.InvalidArgument, format, args...)
}

// classLayer is the StorageClass-level configuration: the referenced CRs and
// the class documents (binding overrides for a generated class, parameter
// documents for a hand-written one).
type classLayer struct {
	store    *v1alpha1.PillarStore
	protocol *v1alpha1.PillarProtocol

	backend    *v1alpha1.BackendOverrides
	protocolOv *v1alpha1.ProtocolOverrides

	// filesystem is the class filesystem document (binding
	// spec.filesystem, or a hand-written class's filesystem parameter).
	filesystem *v1alpha1.FilesystemConfig

	// source names the class layer in error messages.
	source string

	// localAttach is the class's local attach setting (binding
	// spec.localAttach, or a hand-written class's local-attach parameter).
	localAttach bool
	driverName  string

	// storeName is the PillarStore the class names (loaded into store only
	// when the store is resolved).
	storeName string
}

// resolution is the outcome of resolveVolumeConfig.
type resolution struct {
	// resolved is the effective configuration.
	resolved *v1alpha1.ResolvedVolumeConfig

	// agentRef is the PillarAgent that hosts the store.
	agentRef string

	// pvcFS is the claim's filesystem document (nil when the claim sets
	// none); CreateVolume rejects it for a raw block volume.
	pvcFS *v1alpha1.FilesystemConfig

	// storeName is the PillarStore the StorageClass names.
	storeName string

	// importDataset is the raw value of the claim's
	// v1alpha1.AnnotationImportZvol annotation ("" when absent).  CreateVolume
	// validates it against the resolved backend and switches the backend step
	// from create to adopt.
	importDataset    string
	importDirectory  string
	importZFSDataset string
}

// resolveVolumeConfig resolves the effective configuration of a new volume
// from the StorageClass parameters, the CRs they reference and the claim's
// annotations.  Errors are gRPC status errors: InvalidArgument for a bad
// parameter or document, FailedPrecondition for a referenced CR (or claim)
// that does not exist, Internal otherwise.
//
// When recorded is non-nil (a retry of a lifecycle whose first attempt
// already recorded its resolution) only the export settings are resolved
// from the live CRs: the backend, filesystem and local attach setting come
// from recorded, so a later store, filesystem or class change can neither
// block nor alter the retry of a volume whose backend already exists.
func (s *ControllerServer) resolveVolumeConfig(
	ctx context.Context,
	scParams map[string]string,
	caps []*csi.VolumeCapability,
	recorded *v1alpha1.ResolvedVolumeConfig,
) (*resolution, error) {
	class, err := s.resolveClassLayer(ctx, scParams, recorded == nil)
	if err != nil {
		return nil, err
	}
	pvc, err := s.claimDocs(ctx, scParams, false)
	if err != nil {
		return nil, err
	}

	protocol, err := resolveProtocol(class, pvc)
	if err != nil {
		return nil, err
	}
	if recorded != nil {
		return replayResolution(class, pvc, protocol, recorded)
	}

	backend := *class.store.Spec.Backend.DeepCopy()
	for _, layer := range []struct {
		source string
		ov     *v1alpha1.BackendOverrides
	}{
		{class.source, class.backend},
		{configdocs.BackendDocKey + " (PVC annotation)", pvc.Backend},
	} {
		err = applyBackendOverride(&backend, layer.ov, layer.source)
		if err != nil {
			return nil, invalidConfig("%v", err)
		}
	}
	if lvm := backend.LVM; lvm != nil && lvm.ProvisioningMode == "" {
		// The single LVM default (the CRD default), applied on every path.
		lvm.ProvisioningMode = v1alpha1.LVMProvisioningModeLinear
	}
	if lvm := backend.LVM; lvm != nil &&
		lvm.ProvisioningMode == v1alpha1.LVMProvisioningModeThin && lvm.ThinPool == "" {
		return nil, invalidConfig(
			"lvm.provisioningMode thin requires PillarStore %q to set lvm.thinPool", class.store.Name)
	}

	fs, err := resolveProtocolFilesystem(scParams, caps, class, pvc.Filesystem, protocol.Kind())
	if err != nil {
		return nil, err
	}

	return &resolution{
		resolved: &v1alpha1.ResolvedVolumeConfig{
			Backend:     backend,
			Protocol:    protocol,
			Filesystem:  fs,
			LocalAttach: class.localAttach,
		},
		agentRef:         class.store.Spec.AgentRef,
		pvcFS:            pvc.Filesystem,
		storeName:        class.storeName,
		importDataset:    pvc.ImportZvol,
		importDirectory:  pvc.ImportDirectory,
		importZFSDataset: pvc.ImportZFSDataset,
	}, nil
}

func resolveProtocolFilesystem(
	scParams map[string]string,
	caps []*csi.VolumeCapability,
	class *classLayer,
	pvcFS *v1alpha1.FilesystemConfig,
	protocol v1alpha1.ProtocolID,
) (*v1alpha1.FilesystemConfig, error) {
	fs, err := resolveFilesystem(scParams, caps, class.filesystem, pvcFS)
	if err != nil {
		return nil, err
	}
	if protocol != v1alpha1.ProtocolIDNFS {
		return fs, nil
	}
	err = validateNFSFilesystem(scParams, caps, class.filesystem, pvcFS)
	if err != nil {
		return nil, invalidConfig("%v", err)
	}
	if class.localAttach && class.driverName != v1alpha1.FileCSIDriver {
		return nil, invalidConfig("localAttach is not supported for protocol %q", v1alpha1.ProtocolIDNFS)
	}
	fs.FSType = ProtocolNFS
	return fs, nil
}

// resolveProtocol applies the class and claim protocol overrides to the
// referenced PillarProtocol's configuration.  An NVMe-oF/TCP
// maxDataTransferSize no layer sets resolves to
// v1alpha1.DefaultMaxDataTransferSize, so the target advertises (and the
// node enforces) the default limit and the recorded value stays fixed for
// the volume's lifetime.
func resolveProtocol(class *classLayer, pvc pvcDocs) (v1alpha1.ProtocolSpec, error) {
	protocol := *class.protocol.Spec.Protocol.DeepCopy()
	for _, layer := range []struct {
		source string
		ov     *v1alpha1.ProtocolOverrides
	}{
		{class.source, class.protocolOv},
		{configdocs.ProtocolDocKey + " (PVC annotation)", pvc.Protocol},
	} {
		err := applyProtocolOverride(&protocol, layer.ov, layer.source)
		if err != nil {
			return v1alpha1.ProtocolSpec{}, invalidConfig("%v", err)
		}
	}
	if n := protocol.NVMeOFTCP; n != nil && n.MaxDataTransferSize == nil {
		v := v1alpha1.DefaultMaxDataTransferSize
		n.MaxDataTransferSize = &v
	}
	return protocol, nil
}

// replayResolution is the resolution of a retry: the recorded configuration
// with the export settings of the live protocol.  The protocol member and
// the iSCSI authentication stay as recorded: auth is fixed per volume at the
// first attempt, so a PillarProtocol auth change after it cannot change
// which credentials the volume's export (and its nodes) use.
func replayResolution(
	class *classLayer,
	pvc pvcDocs,
	protocol v1alpha1.ProtocolSpec,
	recorded *v1alpha1.ResolvedVolumeConfig,
) (*resolution, error) {
	if protocol.Kind() != recorded.Protocol.Kind() {
		return nil, status.Errorf(codes.FailedPrecondition,
			"PillarProtocol %q now configures %q but the volume was provisioned over %q",
			class.protocol.Name, protocol.Kind(), recorded.Protocol.Kind())
	}
	exportOnly := recorded.DeepCopy()
	exportOnly.Protocol = protocol
	if iscsi := exportOnly.Protocol.ISCSI; iscsi != nil && recorded.Protocol.ISCSI != nil {
		iscsi.Auth = recorded.Protocol.ISCSI.Auth.DeepCopy()
	}
	return &resolution{resolved: exportOnly, pvcFS: pvc.Filesystem, storeName: class.storeName,
		importDataset: pvc.ImportZvol, importDirectory: pvc.ImportDirectory,
		importZFSDataset: pvc.ImportZFSDataset}, nil
}

// resolveClassLayer reads the StorageClass identity parameters and loads the
// CRs and class documents they name.  The PillarStore is loaded only when
// withStore is true (a first attempt); a retry reuses the recorded backend.
func (s *ControllerServer) resolveClassLayer(
	ctx context.Context,
	scParams map[string]string,
	withStore bool,
) (*classLayer, error) {
	bindingName := scParams[paramBinding]
	if bindingName != "" {
		err := rejectUnknownPillarKeys("StorageClass parameter", scParams, generatedClassParams)
		if err != nil {
			return nil, invalidConfig("%v (a class generated by PillarStorageClass %q carries only %s)",
				err, bindingName, paramBinding)
		}
		binding := &v1alpha1.PillarStorageClass{}
		err = s.getCR(ctx, bindingName, binding, "PillarStorageClass", paramBinding)
		if err != nil {
			return nil, err
		}
		if binding.Spec.EffectiveCSIDriver() != s.effectiveDriverName() {
			return nil, invalidConfig("PillarStorageClass %q selects CSI driver %q, not %q",
				bindingName, binding.Spec.EffectiveCSIDriver(), s.effectiveDriverName())
		}
		class := &classLayer{
			filesystem:  binding.Spec.Filesystem,
			source:      fmt.Sprintf("PillarStorageClass %q spec.overrides", bindingName),
			localAttach: binding.Spec.LocalAttach,
			driverName:  s.effectiveDriverName(),
		}
		if ov := binding.Spec.Overrides; ov != nil {
			class.backend, class.protocolOv = ov.Backend, ov.Protocol
		}
		err = s.loadStoreAndProtocol(ctx, class, binding.Spec.StoreRef, binding.Spec.ProtocolRef, withStore)
		if err != nil {
			return nil, err
		}
		return class, nil
	}

	err := rejectUnknownPillarKeys("StorageClass parameter", scParams, handWrittenClassParams)
	if err != nil {
		return nil, invalidConfig("%v", err)
	}
	storeName, protocolName := scParams[paramStoreRef], scParams[paramProtocolRef]
	if storeName == "" || protocolName == "" {
		return nil, invalidConfig(
			"StorageClass parameters must name the configuration: either %q (generated by a "+
				"PillarStorageClass) or both %q and %q",
			paramBinding, paramStoreRef, paramProtocolRef)
	}

	class := &classLayer{source: "StorageClass parameter", driverName: s.effectiveDriverName()}
	backendDoc, err := configdocs.DecodeBackendOverride(
		paramBackendDoc+" (StorageClass parameter)", scParams[paramBackendDoc])
	if err != nil {
		return nil, invalidConfig("%v", err)
	}
	protocolDoc, err := configdocs.DecodeProtocolOverride(
		paramProtocolDoc+" (StorageClass parameter)", scParams[paramProtocolDoc])
	if err != nil {
		return nil, invalidConfig("%v", err)
	}
	filesystemDoc, err := configdocs.DecodeFilesystemDoc(
		paramFilesystemDoc+" (StorageClass parameter)", scParams[paramFilesystemDoc])
	if err != nil {
		return nil, invalidConfig("%v", err)
	}
	localAttach, err := parseLocalAttachParam(scParams)
	if err != nil {
		return nil, err
	}
	class.backend, class.protocolOv, class.filesystem = backendDoc, protocolDoc, filesystemDoc
	class.localAttach = localAttach
	err = s.loadStoreAndProtocol(ctx, class, storeName, protocolName, withStore)
	if err != nil {
		return nil, err
	}
	return class, nil
}

// parseLocalAttachParam reads a hand-written class's local-attach
// parameter: "true" or "false", absent is false, anything else is
// InvalidArgument.
func parseLocalAttachParam(scParams map[string]string) (bool, error) {
	raw, ok := scParams[paramLocalAttach]
	if !ok {
		return false, nil
	}
	switch raw {
	case topologyValueTrue:
		return true, nil
	case "false":
		return false, nil
	default:
		return false, invalidConfig("StorageClass parameter %s = %q: must be %q or \"false\"",
			paramLocalAttach, raw, topologyValueTrue)
	}
}

// loadStoreAndProtocol fetches the named PillarProtocol and, when withStore
// is true, the named PillarStore and checks the pair is compatible.
func (s *ControllerServer) loadStoreAndProtocol(
	ctx context.Context,
	class *classLayer,
	storeName, protocolName string,
	withStore bool,
) error {
	class.storeName = storeName
	class.protocol = &v1alpha1.PillarProtocol{}
	err := s.getCR(ctx, protocolName, class.protocol, "PillarProtocol", paramProtocolRef)
	if err != nil {
		return err
	}
	if class.protocol.Spec.Protocol.Kind() == "" {
		return invalidConfig("PillarProtocol %q: spec.protocol sets no protocol member", protocolName)
	}
	if !withStore {
		return nil
	}
	class.store = &v1alpha1.PillarStore{}
	err = s.getCR(ctx, storeName, class.store, "PillarStore", paramStoreRef)
	if err != nil {
		return err
	}
	if class.store.Spec.Backend.Kind() == "" {
		return invalidConfig("PillarStore %q: spec.backend sets no backend member", storeName)
	}
	if class.store.Spec.Backend.Directory != nil && s.effectiveDriverName() != v1alpha1.FileCSIDriver {
		return invalidConfig("PillarStore %q directory backend requires CSI driver %q", storeName, v1alpha1.FileCSIDriver)
	}
	compat := v1alpha1.Compatible(class.store.Spec.Backend, class.protocol.Spec.Protocol)
	if !compat.OK {
		return invalidConfig("PillarStore %q / PillarProtocol %q: %s", storeName, protocolName, compat.Message)
	}
	return nil
}

// getCR reads a cluster-scoped CR by name.  A missing CR is
// FailedPrecondition (the provisioner retries once it exists).
func (s *ControllerServer) getCR(ctx context.Context, name string, obj client.Object, kind, via string) error {
	err := s.k8sClient.Get(ctx, types.NamespacedName{Name: name}, obj)
	if err == nil {
		return nil
	}
	if k8serrors.IsNotFound(err) {
		return status.Errorf(codes.FailedPrecondition, "%s %q (named via %s) not found", kind, name, via)
	}
	return status.Errorf(codes.Internal, "get %s %q: %v", kind, name, err)
}

// claimDocs decodes the configuration documents of the claim identified by
// the external-provisioner's --extra-create-metadata parameters.  Without
// that metadata no claim is known and the layer is empty. A named claim that
// cannot be read is an error unless allowAbsent permits only NotFound for a
// completed lifecycle whose recorded adoption remains authoritative.
func (s *ControllerServer) claimDocs(
	ctx context.Context, scParams map[string]string, allowAbsent bool,
) (pvcDocs, error) {
	pvcName, pvcNamespace := scParams[paramPVCNameMeta], scParams[paramPVCNamespaceMeta]
	if pvcName == "" || pvcNamespace == "" {
		return pvcDocs{}, nil
	}
	pvc := &corev1.PersistentVolumeClaim{}
	err := s.apiReader.Get(ctx, types.NamespacedName{Namespace: pvcNamespace, Name: pvcName}, pvc)
	if err != nil {
		if k8serrors.IsNotFound(err) {
			if allowAbsent {
				return pvcDocs{}, nil
			}
			return pvcDocs{}, status.Errorf(codes.FailedPrecondition,
				"PersistentVolumeClaim %s/%s not found", pvcNamespace, pvcName)
		}
		return pvcDocs{}, status.Errorf(codes.Internal,
			"get PersistentVolumeClaim %s/%s: %v", pvcNamespace, pvcName, err)
	}
	docs, err := decodePVCAnnotations(pvc.Annotations)
	if err != nil {
		return pvcDocs{}, invalidConfig("PVC %s/%s annotation validation failed: %v", pvcNamespace, pvcName, err)
	}
	return docs, nil
}

// applyBackendOverride applies an override document onto the effective
// backend.  The override member must match the backend member.
func applyBackendOverride(backend *v1alpha1.BackendSpec, ov *v1alpha1.BackendOverrides, source string) error {
	if ov == nil {
		return nil
	}
	switch {
	case ov.ZFS != nil:
		if backend.ZFS == nil {
			return fmt.Errorf("%s: zfs overrides do not apply to a %s backend", source, backend.Kind())
		}
		if len(ov.ZFS.Properties) > 0 {
			props := make(map[string]string, len(backend.ZFS.Properties)+len(ov.ZFS.Properties))
			maps.Copy(props, backend.ZFS.Properties)
			maps.Copy(props, ov.ZFS.Properties)
			backend.ZFS.Properties = props
		}
	case ov.LVM != nil:
		if backend.LVM == nil {
			return fmt.Errorf("%s: lvm overrides do not apply to a %s backend", source, backend.Kind())
		}
		if ov.LVM.ProvisioningMode != "" {
			backend.LVM.ProvisioningMode = ov.LVM.ProvisioningMode
		}
	case ov.Directory != nil:
		if backend.Directory == nil {
			return fmt.Errorf("%s: directory overrides do not apply to a %s backend", source, backend.Kind())
		}
	}
	return nil
}

// int32Override pairs an effective tunable with its override value; a nil
// src leaves dst unchanged.
type int32Override struct {
	dst **int32
	src *int32
}

// applyProtocolOverride applies an override document onto the effective
// protocol.  The override member must match the protocol member.
func applyProtocolOverride(protocol *v1alpha1.ProtocolSpec, ov *v1alpha1.ProtocolOverrides, source string) error {
	if ov == nil {
		return nil
	}
	var fields []int32Override
	switch {
	case ov.NVMeOFTCP != nil:
		if protocol.NVMeOFTCP == nil {
			return fmt.Errorf("%s: nvmeofTcp overrides do not apply to a %s protocol", source, protocol.Kind())
		}
		dst, src := protocol.NVMeOFTCP, ov.NVMeOFTCP
		fields = []int32Override{
			{&dst.MaxQueueSize, src.MaxQueueSize},
			{&dst.InCapsuleDataSize, src.InCapsuleDataSize},
			{&dst.MaxDataTransferSize, src.MaxDataTransferSize},
			{&dst.CtrlLossTmo, src.CtrlLossTmo},
			{&dst.ReconnectDelay, src.ReconnectDelay},
		}
	case ov.ISCSI != nil:
		if protocol.ISCSI == nil {
			return fmt.Errorf("%s: iscsi overrides do not apply to a %s protocol", source, protocol.Kind())
		}
		dst, src := protocol.ISCSI, ov.ISCSI
		fields = []int32Override{
			{&dst.LoginTimeout, src.LoginTimeout},
			{&dst.ReplacementTimeout, src.ReplacementTimeout},
			{&dst.NoopOutInterval, src.NoopOutInterval},
			{&dst.NoopOutTimeout, src.NoopOutTimeout},
		}
	case ov.NFS != nil:
		if protocol.NFS == nil {
			return fmt.Errorf("%s: nfs overrides do not apply to a %s protocol", source, protocol.Kind())
		}
	}
	for _, f := range fields {
		if f.src != nil {
			v := *f.src
			*f.dst = &v
		}
	}
	return nil
}

// resolveFilesystem layers the filesystem documents: ext4 default, the
// class document (with a hand-written class's csi.storage.k8s.io/fstype),
// then the PVC document.  Lists follow list semantics: nil inherits, an
// explicit empty list clears.  Caps are the request's volume capabilities:
// the external-provisioner delivers the class's csi.storage.k8s.io/fstype as
// the mount capability's fsType (it strips csi.storage.k8s.io/* keys from
// the parameters).
func resolveFilesystem(
	scParams map[string]string,
	caps []*csi.VolumeCapability,
	classFS, pvcFS *v1alpha1.FilesystemConfig,
) (*v1alpha1.FilesystemConfig, error) {
	capFSType, err := capabilityFSType(caps)
	if err != nil {
		return nil, err
	}
	fs, err := classFilesystemBase(scParams, capFSType, classFS)
	if err != nil {
		return nil, err
	}
	for _, layer := range []*v1alpha1.FilesystemConfig{classFS, pvcFS} {
		if layer == nil {
			continue
		}
		if layer.FSType != "" {
			fs.FSType = layer.FSType
		}
		if layer.MkfsOptions != nil {
			fs.MkfsOptions = copyList(layer.MkfsOptions)
		}
		if layer.MountOptions != nil {
			fs.MountOptions = copyList(layer.MountOptions)
		}
		if layer.PeriodicTrim != nil {
			v := *layer.PeriodicTrim
			fs.PeriodicTrim = &v
		}
	}
	return fs, nil
}

// classFilesystemBase is the filesystem configuration below the class
// document: the ext4 default and, for a hand-written class, its
// csi.storage.k8s.io/fstype.  The external-provisioner removes that key from
// the CreateVolume parameters and passes its value as the mount
// capability's fsType (capFSType); the parameter itself is still honored
// for callers that send it directly, and both must agree.  A generated
// class's fstype and mountOptions are only copies of the live binding's
// spec.filesystem (and may be stale), so a generated class starts from ext4
// and an explicit empty mount list, which keeps a stale copy from reaching
// the node through the capability.
func classFilesystemBase(
	scParams map[string]string,
	capFSType string,
	classFS *v1alpha1.FilesystemConfig,
) (*v1alpha1.FilesystemConfig, error) {
	fs := &v1alpha1.FilesystemConfig{FSType: defaultFsType}
	if scParams[paramBinding] != "" {
		fs.MountOptions = &[]string{}
		return fs, nil
	}
	scFSType := scParams[paramFSTypeSC]
	if scFSType != "" && capFSType != "" && scFSType != capFSType {
		return nil, invalidConfig("StorageClass parameter %s %q conflicts with the volume capability fsType %q",
			paramFSTypeSC, scFSType, capFSType)
	}
	if scFSType == "" {
		scFSType = capFSType
	}
	if scFSType == "" {
		return fs, nil
	}
	if scFSType != defaultFsType && scFSType != xfsFsType && scFSType != string(v1alpha1.ProtocolIDNFS) {
		return nil, invalidConfig("unsupported StorageClass parameter %s %q: must be %q, %q or %q",
			paramFSTypeSC, scFSType, defaultFsType, xfsFsType, v1alpha1.ProtocolIDNFS)
	}
	if classFS != nil && classFS.FSType != "" && classFS.FSType != scFSType {
		return nil, invalidConfig("StorageClass parameter %s fsType %q conflicts with %s %q",
			paramFilesystemDoc, classFS.FSType, paramFSTypeSC, scFSType)
	}
	fs.FSType = scFSType
	return fs, nil
}

// validateNFSFilesystem rejects filesystem settings that the file protocol
// cannot apply.  An omitted filesystem document is valid; the effective
// filesystem type is supplied by resolveVolumeConfig as "nfs".
func validateNFSFilesystem(
	scParams map[string]string,
	caps []*csi.VolumeCapability,
	classFS, pvcFS *v1alpha1.FilesystemConfig,
) error {
	if scType := scParams[paramFSTypeSC]; scType != "" && scType != ProtocolNFS {
		return fmt.Errorf("filesystem fsType %q is not supported for NFS volumes", scType)
	}
	for _, cap := range caps {
		if fsType := cap.GetMount().GetFsType(); fsType != "" && fsType != ProtocolNFS {
			return fmt.Errorf("volume capability fsType %q is not supported for NFS volumes", fsType)
		}
	}
	for source, fs := range map[string]*v1alpha1.FilesystemConfig{
		"StorageClass": classFS,
		"PVC":          pvcFS,
	} {
		if fs == nil {
			continue
		}
		if fs.FSType != "" && fs.FSType != "nfs" {
			return fmt.Errorf("%s filesystem fsType %q is not supported for NFS volumes", source, fs.FSType)
		}
		if len(derefList(fs.MkfsOptions)) != 0 {
			return fmt.Errorf("%s filesystem mkfsOptions are not supported for NFS volumes", source)
		}
		if fs.PeriodicTrim != nil && *fs.PeriodicTrim {
			return fmt.Errorf("%s filesystem periodicTrim=true is not supported for NFS volumes", source)
		}
	}
	return nil
}

// capabilityFSType returns the fsType the request's mount capabilities name
// ("" when none does).  Capabilities naming different fsTypes are
// InvalidArgument.
func capabilityFSType(caps []*csi.VolumeCapability) (string, error) {
	fsType := ""
	for _, c := range caps {
		v := c.GetMount().GetFsType()
		if v == "" || v == fsType {
			continue
		}
		if fsType != "" {
			return "", invalidConfig("volume capabilities name conflicting fsTypes %q and %q", fsType, v)
		}
		fsType = v
	}
	return fsType, nil
}

func copyList(p *[]string) *[]string {
	out := append([]string{}, (*p)...)
	return &out
}

// nodeVolumeContext returns the VolumeContext entries derived from the
// resolved configuration that the node needs at stage time: NVMe-oF connect
// or iSCSI session tuning, NFS protocol version, the iSCSI authentication
// method (absent for None) and the filesystem settings.
func nodeVolumeContext(resolved *v1alpha1.ResolvedVolumeConfig, volCtx map[string]string) {
	if resolved == nil {
		return
	}
	var tuning []int32ContextEntry
	switch {
	case resolved.Protocol.NVMeOFTCP != nil:
		n := resolved.Protocol.NVMeOFTCP
		tuning = []int32ContextEntry{
			{paramNVMeOFCtrlLossTmo, n.CtrlLossTmo},
			{paramNVMeOFReconnectDelay, n.ReconnectDelay},
			{paramNVMeOFMaxQueueSize, n.MaxQueueSize},
			{paramNVMeOFMaxDataTransferSize, n.MaxDataTransferSize},
		}
	case resolved.Protocol.ISCSI != nil:
		i := resolved.Protocol.ISCSI
		tuning = []int32ContextEntry{
			{VolumeContextKeyISCSILoginTimeout, i.LoginTimeout},
			{VolumeContextKeyISCSIReplacementTimeout, i.ReplacementTimeout},
			{VolumeContextKeyISCSINoopOutInterval, i.NoopOutInterval},
			{VolumeContextKeyISCSINoopOutTimeout, i.NoopOutTimeout},
		}
		if method := i.Auth.EffectiveMethod(); method != v1alpha1.ISCSIAuthMethodNone {
			volCtx[VolumeContextKeyISCSIAuthMethod] = string(method)
		}
	case resolved.Protocol.NFS != nil:
		version := resolved.Protocol.NFS.Version
		if version == "" {
			version = "4.2"
		}
		volCtx[paramNFSVersion] = version
	}
	for _, f := range tuning {
		if f.v != nil {
			volCtx[f.key] = strconv.FormatInt(int64(*f.v), 10)
		}
	}
	filesystemVolumeContext(resolved.Filesystem, volCtx)
}

// int32ContextEntry is a VolumeContext key and its optional resolved value.
type int32ContextEntry struct {
	key string
	v   *int32
}
