# This rule is not used by the project pillar-csi itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the pillar-csi.pillar-csi.bhyoo.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pillar-csi
    app.kubernetes.io/managed-by: kustomize
  name: pillartarget-editor-role
rules:
- apiGroups:
  - pillar-csi.pillar-csi.bhyoo.com
  resources:
  - pillartargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pillar-csi.pillar-csi.bhyoo.com
  resources:
  - pillartargets/status
  verbs:
  - get
