---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pillar-csi.bhyoo.com
  resources:
  - pillaragents
  - pillarprotocols
  - pillarstorageclasses
  - pillarstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pillar-csi.bhyoo.com
  resources:
  - pillaragents/finalizers
  - pillarprotocols/finalizers
  - pillarstorageclasses/finalizers
  - pillarstores/finalizers
  verbs:
  - update
- apiGroups:
  - pillar-csi.bhyoo.com
  resources:
  - pillaragents/status
  - pillarprotocols/status
  - pillarstorageclasses/status
  - pillarstores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
