---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pillar-csi.pillar-csi.bhyoo.com
  resources:
  - pillarpools
  - pillartargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pillar-csi.pillar-csi.bhyoo.com
  resources:
  - pillarpools/finalizers
  - pillartargets/finalizers
  verbs:
  - update
- apiGroups:
  - pillar-csi.pillar-csi.bhyoo.com
  resources:
  - pillarpools/status
  - pillartargets/status
  verbs:
  - get
  - patch
  - update
