---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pillar-csi.pillar-csi.bhyoo.com
  resources:
  - pillarbindings
  - pillarpools
  - pillarprotocols
  - pillartargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pillar-csi.pillar-csi.bhyoo.com
  resources:
  - pillarbindings/finalizers
  - pillarpools/finalizers
  - pillarprotocols/finalizers
  - pillartargets/finalizers
  verbs:
  - update
- apiGroups:
  - pillar-csi.pillar-csi.bhyoo.com
  resources:
  - pillarbindings/status
  - pillarpools/status
  - pillarprotocols/status
  - pillartargets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
