{{- define "gvList" -}}
{{- $groupVersions := . -}}
---
title: CRD reference
description: "Field reference for the pillar-csi v1alpha1 CRDs: PillarAgent, PillarStore, PillarProtocol, PillarStorageClass and PillarVolumeState, from the Go types."
sidebar:
  order: 3
---

<!-- Generated by `make docs-gen` from api/v1alpha1 with crd-ref-docs. Do not edit by hand. -->

All pillar-csi resources are cluster-scoped. The controller manages PillarVolumeState objects; do not create them by hand.

## Packages
{{- range $groupVersions }}
- {{ markdownRenderGVLink . }}
{{- end }}

{{ range $groupVersions }}
{{ template "gvDetails" . }}
{{ end }}

{{- end -}}
