## Append samples of your project ##
resources:
- pillar-csi_v1alpha1_pillaragent.yaml
- pillar-csi_v1alpha1_pillarstore.yaml
- pillar-csi_v1alpha1_pillarprotocol.yaml
- pillar-csi_v1alpha1_pillarstorageclass.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
