apiVersion: pillar-csi.pillar-csi.bhyoo.com/v1alpha1
kind: PillarTarget
metadata:
  labels:
    app.kubernetes.io/name: pillar-csi
    app.kubernetes.io/managed-by: kustomize
  name: pillartarget-sample
spec:
  # TODO(user): Add fields here
