apiVersion: pillar-csi.bhyoo.com/v1alpha1
kind: PillarProtocol
metadata:
  labels:
    app.kubernetes.io/name: pillar-csi
    app.kubernetes.io/managed-by: kustomize
  name: pillarprotocol-sample
spec:
  # Exactly one protocol member.
  protocol:
    nvmeofTcp:
      port: 4420
      acl: false
      maxQueueSize: 128
      ctrlLossTmo: 1200
      reconnectDelay: 5
