apiVersion: pillar-csi.bhyoo.com/v1alpha1
kind: PillarStorageClass
metadata:
  labels:
    app.kubernetes.io/name: pillar-csi
    app.kubernetes.io/managed-by: kustomize
  name: pillarstorageclass-sample
spec:
  # TODO(user): Add fields here
