//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCapabilities) DeepCopyInto(out *AgentCapabilities) {
	*out = *in
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCapabilities.
func (in *AgentCapabilities) DeepCopy() *AgentCapabilities {
	if in == nil {
		return nil
	}
	out := new(AgentCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendOverrides) DeepCopyInto(out *BackendOverrides) {
	*out = *in
	if in.ZFS != nil {
		in, out := &in.ZFS, &out.ZFS
		*out = new(ZFSPropertyOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendOverrides.
func (in *BackendOverrides) DeepCopy() *BackendOverrides {
	if in == nil {
		return nil
	}
	out := new(BackendOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
	if in.ZFS != nil {
		in, out := &in.ZFS, &out.ZFS
		*out = new(ZFSBackendConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendSpec.
func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingOverrides) DeepCopyInto(out *BindingOverrides) {
	*out = *in
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(BackendOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(ProtocolOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.MkfsOptions != nil {
		in, out := &in.MkfsOptions, &out.MkfsOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingOverrides.
func (in *BindingOverrides) DeepCopy() *BindingOverrides {
	if in == nil {
		return nil
	}
	out := new(BindingOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredPool) DeepCopyInto(out *DiscoveredPool) {
	*out = *in
	if in.Total != nil {
		in, out := &in.Total, &out.Total
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredPool.
func (in *DiscoveredPool) DeepCopy() *DiscoveredPool {
	if in == nil {
		return nil
	}
	out := new(DiscoveredPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSpec) DeepCopyInto(out *ExternalSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSpec.
func (in *ExternalSpec) DeepCopy() *ExternalSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISCSIConfig) DeepCopyInto(out *ISCSIConfig) {
	*out = *in
	if in.LoginTimeout != nil {
		in, out := &in.LoginTimeout, &out.LoginTimeout
		*out = new(int32)
		**out = **in
	}
	if in.ReplacementTimeout != nil {
		in, out := &in.ReplacementTimeout, &out.ReplacementTimeout
		*out = new(int32)
		**out = **in
	}
	if in.NodeSessionTimeout != nil {
		in, out := &in.NodeSessionTimeout, &out.NodeSessionTimeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISCSIConfig.
func (in *ISCSIConfig) DeepCopy() *ISCSIConfig {
	if in == nil {
		return nil
	}
	out := new(ISCSIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISCSIOverrides) DeepCopyInto(out *ISCSIOverrides) {
	*out = *in
	if in.LoginTimeout != nil {
		in, out := &in.LoginTimeout, &out.LoginTimeout
		*out = new(int32)
		**out = **in
	}
	if in.ReplacementTimeout != nil {
		in, out := &in.ReplacementTimeout, &out.ReplacementTimeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISCSIOverrides.
func (in *ISCSIOverrides) DeepCopy() *ISCSIOverrides {
	if in == nil {
		return nil
	}
	out := new(ISCSIOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFSConfig) DeepCopyInto(out *NFSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFSConfig.
func (in *NFSConfig) DeepCopy() *NFSConfig {
	if in == nil {
		return nil
	}
	out := new(NFSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVMeOFTCPConfig) DeepCopyInto(out *NVMeOFTCPConfig) {
	*out = *in
	if in.MaxQueueSize != nil {
		in, out := &in.MaxQueueSize, &out.MaxQueueSize
		*out = new(int32)
		**out = **in
	}
	if in.InCapsuleDataSize != nil {
		in, out := &in.InCapsuleDataSize, &out.InCapsuleDataSize
		*out = new(int32)
		**out = **in
	}
	if in.CtrlLossTmo != nil {
		in, out := &in.CtrlLossTmo, &out.CtrlLossTmo
		*out = new(int32)
		**out = **in
	}
	if in.ReconnectDelay != nil {
		in, out := &in.ReconnectDelay, &out.ReconnectDelay
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVMeOFTCPConfig.
func (in *NVMeOFTCPConfig) DeepCopy() *NVMeOFTCPConfig {
	if in == nil {
		return nil
	}
	out := new(NVMeOFTCPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVMeOFTCPOverrides) DeepCopyInto(out *NVMeOFTCPOverrides) {
	*out = *in
	if in.MaxQueueSize != nil {
		in, out := &in.MaxQueueSize, &out.MaxQueueSize
		*out = new(int32)
		**out = **in
	}
	if in.InCapsuleDataSize != nil {
		in, out := &in.InCapsuleDataSize, &out.InCapsuleDataSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVMeOFTCPOverrides.
func (in *NVMeOFTCPOverrides) DeepCopy() *NVMeOFTCPOverrides {
	if in == nil {
		return nil
	}
	out := new(NVMeOFTCPOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRefSpec) DeepCopyInto(out *NodeRefSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRefSpec.
func (in *NodeRefSpec) DeepCopy() *NodeRefSpec {
	if in == nil {
		return nil
	}
	out := new(NodeRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarBinding) DeepCopyInto(out *PillarBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarBinding.
func (in *PillarBinding) DeepCopy() *PillarBinding {
	if in == nil {
		return nil
	}
	out := new(PillarBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarBindingList) DeepCopyInto(out *PillarBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PillarBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarBindingList.
func (in *PillarBindingList) DeepCopy() *PillarBindingList {
	if in == nil {
		return nil
	}
	out := new(PillarBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarBindingSpec) DeepCopyInto(out *PillarBindingSpec) {
	*out = *in
	in.StorageClass.DeepCopyInto(&out.StorageClass)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(BindingOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarBindingSpec.
func (in *PillarBindingSpec) DeepCopy() *PillarBindingSpec {
	if in == nil {
		return nil
	}
	out := new(PillarBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarBindingStatus) DeepCopyInto(out *PillarBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarBindingStatus.
func (in *PillarBindingStatus) DeepCopy() *PillarBindingStatus {
	if in == nil {
		return nil
	}
	out := new(PillarBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarPool) DeepCopyInto(out *PillarPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarPool.
func (in *PillarPool) DeepCopy() *PillarPool {
	if in == nil {
		return nil
	}
	out := new(PillarPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarPoolList) DeepCopyInto(out *PillarPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PillarPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarPoolList.
func (in *PillarPoolList) DeepCopy() *PillarPoolList {
	if in == nil {
		return nil
	}
	out := new(PillarPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarPoolSpec) DeepCopyInto(out *PillarPoolSpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarPoolSpec.
func (in *PillarPoolSpec) DeepCopy() *PillarPoolSpec {
	if in == nil {
		return nil
	}
	out := new(PillarPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarPoolStatus) DeepCopyInto(out *PillarPoolStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(PoolCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarPoolStatus.
func (in *PillarPoolStatus) DeepCopy() *PillarPoolStatus {
	if in == nil {
		return nil
	}
	out := new(PillarPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarProtocol) DeepCopyInto(out *PillarProtocol) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarProtocol.
func (in *PillarProtocol) DeepCopy() *PillarProtocol {
	if in == nil {
		return nil
	}
	out := new(PillarProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarProtocol) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarProtocolList) DeepCopyInto(out *PillarProtocolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PillarProtocol, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarProtocolList.
func (in *PillarProtocolList) DeepCopy() *PillarProtocolList {
	if in == nil {
		return nil
	}
	out := new(PillarProtocolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarProtocolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarProtocolSpec) DeepCopyInto(out *PillarProtocolSpec) {
	*out = *in
	if in.NVMeOFTCP != nil {
		in, out := &in.NVMeOFTCP, &out.NVMeOFTCP
		*out = new(NVMeOFTCPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ISCSI != nil {
		in, out := &in.ISCSI, &out.ISCSI
		*out = new(ISCSIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NFS != nil {
		in, out := &in.NFS, &out.NFS
		*out = new(NFSConfig)
		**out = **in
	}
	if in.MkfsOptions != nil {
		in, out := &in.MkfsOptions, &out.MkfsOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarProtocolSpec.
func (in *PillarProtocolSpec) DeepCopy() *PillarProtocolSpec {
	if in == nil {
		return nil
	}
	out := new(PillarProtocolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarProtocolStatus) DeepCopyInto(out *PillarProtocolStatus) {
	*out = *in
	if in.ActiveTargets != nil {
		in, out := &in.ActiveTargets, &out.ActiveTargets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarProtocolStatus.
func (in *PillarProtocolStatus) DeepCopy() *PillarProtocolStatus {
	if in == nil {
		return nil
	}
	out := new(PillarProtocolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarTarget) DeepCopyInto(out *PillarTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarTarget.
func (in *PillarTarget) DeepCopy() *PillarTarget {
	if in == nil {
		return nil
	}
	out := new(PillarTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarTargetList) DeepCopyInto(out *PillarTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PillarTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarTargetList.
func (in *PillarTargetList) DeepCopy() *PillarTargetList {
	if in == nil {
		return nil
	}
	out := new(PillarTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarTargetSpec) DeepCopyInto(out *PillarTargetSpec) {
	*out = *in
	if in.NodeRef != nil {
		in, out := &in.NodeRef, &out.NodeRef
		*out = new(NodeRefSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarTargetSpec.
func (in *PillarTargetSpec) DeepCopy() *PillarTargetSpec {
	if in == nil {
		return nil
	}
	out := new(PillarTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarTargetStatus) DeepCopyInto(out *PillarTargetStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(AgentCapabilities)
		(*in).DeepCopyInto(*out)
	}
	if in.DiscoveredPools != nil {
		in, out := &in.DiscoveredPools, &out.DiscoveredPools
		*out = make([]DiscoveredPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarTargetStatus.
func (in *PillarTargetStatus) DeepCopy() *PillarTargetStatus {
	if in == nil {
		return nil
	}
	out := new(PillarTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolCapacity) DeepCopyInto(out *PoolCapacity) {
	*out = *in
	if in.Total != nil {
		in, out := &in.Total, &out.Total
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Used != nil {
		in, out := &in.Used, &out.Used
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolCapacity.
func (in *PoolCapacity) DeepCopy() *PoolCapacity {
	if in == nil {
		return nil
	}
	out := new(PoolCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolOverrides) DeepCopyInto(out *ProtocolOverrides) {
	*out = *in
	if in.NVMeOFTCP != nil {
		in, out := &in.NVMeOFTCP, &out.NVMeOFTCP
		*out = new(NVMeOFTCPOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.ISCSI != nil {
		in, out := &in.ISCSI, &out.ISCSI
		*out = new(ISCSIOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolOverrides.
func (in *ProtocolOverrides) DeepCopy() *ProtocolOverrides {
	if in == nil {
		return nil
	}
	out := new(ProtocolOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassTemplate) DeepCopyInto(out *StorageClassTemplate) {
	*out = *in
	if in.AllowVolumeExpansion != nil {
		in, out := &in.AllowVolumeExpansion, &out.AllowVolumeExpansion
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassTemplate.
func (in *StorageClassTemplate) DeepCopy() *StorageClassTemplate {
	if in == nil {
		return nil
	}
	out := new(StorageClassTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZFSBackendConfig) DeepCopyInto(out *ZFSBackendConfig) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZFSBackendConfig.
func (in *ZFSBackendConfig) DeepCopy() *ZFSBackendConfig {
	if in == nil {
		return nil
	}
	out := new(ZFSBackendConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZFSPropertyOverrides) DeepCopyInto(out *ZFSPropertyOverrides) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZFSPropertyOverrides.
func (in *ZFSPropertyOverrides) DeepCopy() *ZFSPropertyOverrides {
	if in == nil {
		return nil
	}
	out := new(ZFSPropertyOverrides)
	in.DeepCopyInto(out)
	return out
}
