//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCapabilities) DeepCopyInto(out *AgentCapabilities) {
	*out = *in
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCapabilities.
func (in *AgentCapabilities) DeepCopy() *AgentCapabilities {
	if in == nil {
		return nil
	}
	out := new(AgentCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendOverrides) DeepCopyInto(out *BackendOverrides) {
	*out = *in
	if in.ZFS != nil {
		in, out := &in.ZFS, &out.ZFS
		*out = new(ZFSPropertyOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.LVM != nil {
		in, out := &in.LVM, &out.LVM
		*out = new(LVMOverrides)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendOverrides.
func (in *BackendOverrides) DeepCopy() *BackendOverrides {
	if in == nil {
		return nil
	}
	out := new(BackendOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
	if in.ZFS != nil {
		in, out := &in.ZFS, &out.ZFS
		*out = new(ZFSBackendConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LVM != nil {
		in, out := &in.LVM, &out.LVM
		*out = new(LVMBackendConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendSpec.
func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Compatibility) DeepCopyInto(out *Compatibility) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Compatibility.
func (in *Compatibility) DeepCopy() *Compatibility {
	if in == nil {
		return nil
	}
	out := new(Compatibility)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredPool) DeepCopyInto(out *DiscoveredPool) {
	*out = *in
	if in.Total != nil {
		in, out := &in.Total, &out.Total
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredPool.
func (in *DiscoveredPool) DeepCopy() *DiscoveredPool {
	if in == nil {
		return nil
	}
	out := new(DiscoveredPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSpec) DeepCopyInto(out *ExternalSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSpec.
func (in *ExternalSpec) DeepCopy() *ExternalSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISCSIConfig) DeepCopyInto(out *ISCSIConfig) {
	*out = *in
	if in.LoginTimeout != nil {
		in, out := &in.LoginTimeout, &out.LoginTimeout
		*out = new(int32)
		**out = **in
	}
	if in.ReplacementTimeout != nil {
		in, out := &in.ReplacementTimeout, &out.ReplacementTimeout
		*out = new(int32)
		**out = **in
	}
	if in.NodeSessionTimeout != nil {
		in, out := &in.NodeSessionTimeout, &out.NodeSessionTimeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISCSIConfig.
func (in *ISCSIConfig) DeepCopy() *ISCSIConfig {
	if in == nil {
		return nil
	}
	out := new(ISCSIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISCSIOverrides) DeepCopyInto(out *ISCSIOverrides) {
	*out = *in
	if in.LoginTimeout != nil {
		in, out := &in.LoginTimeout, &out.LoginTimeout
		*out = new(int32)
		**out = **in
	}
	if in.ReplacementTimeout != nil {
		in, out := &in.ReplacementTimeout, &out.ReplacementTimeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISCSIOverrides.
func (in *ISCSIOverrides) DeepCopy() *ISCSIOverrides {
	if in == nil {
		return nil
	}
	out := new(ISCSIOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMBackendConfig) DeepCopyInto(out *LVMBackendConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMBackendConfig.
func (in *LVMBackendConfig) DeepCopy() *LVMBackendConfig {
	if in == nil {
		return nil
	}
	out := new(LVMBackendConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMOverrides) DeepCopyInto(out *LVMOverrides) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMOverrides.
func (in *LVMOverrides) DeepCopy() *LVMOverrides {
	if in == nil {
		return nil
	}
	out := new(LVMOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFSConfig) DeepCopyInto(out *NFSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFSConfig.
func (in *NFSConfig) DeepCopy() *NFSConfig {
	if in == nil {
		return nil
	}
	out := new(NFSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVMeOFTCPConfig) DeepCopyInto(out *NVMeOFTCPConfig) {
	*out = *in
	if in.MaxQueueSize != nil {
		in, out := &in.MaxQueueSize, &out.MaxQueueSize
		*out = new(int32)
		**out = **in
	}
	if in.InCapsuleDataSize != nil {
		in, out := &in.InCapsuleDataSize, &out.InCapsuleDataSize
		*out = new(int32)
		**out = **in
	}
	if in.CtrlLossTmo != nil {
		in, out := &in.CtrlLossTmo, &out.CtrlLossTmo
		*out = new(int32)
		**out = **in
	}
	if in.ReconnectDelay != nil {
		in, out := &in.ReconnectDelay, &out.ReconnectDelay
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVMeOFTCPConfig.
func (in *NVMeOFTCPConfig) DeepCopy() *NVMeOFTCPConfig {
	if in == nil {
		return nil
	}
	out := new(NVMeOFTCPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVMeOFTCPOverrides) DeepCopyInto(out *NVMeOFTCPOverrides) {
	*out = *in
	if in.MaxQueueSize != nil {
		in, out := &in.MaxQueueSize, &out.MaxQueueSize
		*out = new(int32)
		**out = **in
	}
	if in.InCapsuleDataSize != nil {
		in, out := &in.InCapsuleDataSize, &out.InCapsuleDataSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVMeOFTCPOverrides.
func (in *NVMeOFTCPOverrides) DeepCopy() *NVMeOFTCPOverrides {
	if in == nil {
		return nil
	}
	out := new(NVMeOFTCPOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRefSpec) DeepCopyInto(out *NodeRefSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRefSpec.
func (in *NodeRefSpec) DeepCopy() *NodeRefSpec {
	if in == nil {
		return nil
	}
	out := new(NodeRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCFSOverride) DeepCopyInto(out *PVCFSOverride) {
	*out = *in
	if in.MkfsOptions != nil {
		in, out := &in.MkfsOptions, &out.MkfsOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCFSOverride.
func (in *PVCFSOverride) DeepCopy() *PVCFSOverride {
	if in == nil {
		return nil
	}
	out := new(PVCFSOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartialFailureInfo) DeepCopyInto(out *PartialFailureInfo) {
	*out = *in
	in.FailedAt.DeepCopyInto(&out.FailedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartialFailureInfo.
func (in *PartialFailureInfo) DeepCopy() *PartialFailureInfo {
	if in == nil {
		return nil
	}
	out := new(PartialFailureInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarAgent) DeepCopyInto(out *PillarAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarAgent.
func (in *PillarAgent) DeepCopy() *PillarAgent {
	if in == nil {
		return nil
	}
	out := new(PillarAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarAgentList) DeepCopyInto(out *PillarAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PillarAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarAgentList.
func (in *PillarAgentList) DeepCopy() *PillarAgentList {
	if in == nil {
		return nil
	}
	out := new(PillarAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarAgentSpec) DeepCopyInto(out *PillarAgentSpec) {
	*out = *in
	if in.NodeRef != nil {
		in, out := &in.NodeRef, &out.NodeRef
		*out = new(NodeRefSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarAgentSpec.
func (in *PillarAgentSpec) DeepCopy() *PillarAgentSpec {
	if in == nil {
		return nil
	}
	out := new(PillarAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarAgentStatus) DeepCopyInto(out *PillarAgentStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(AgentCapabilities)
		(*in).DeepCopyInto(*out)
	}
	if in.DiscoveredPools != nil {
		in, out := &in.DiscoveredPools, &out.DiscoveredPools
		*out = make([]DiscoveredPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarAgentStatus.
func (in *PillarAgentStatus) DeepCopy() *PillarAgentStatus {
	if in == nil {
		return nil
	}
	out := new(PillarAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarProtocol) DeepCopyInto(out *PillarProtocol) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarProtocol.
func (in *PillarProtocol) DeepCopy() *PillarProtocol {
	if in == nil {
		return nil
	}
	out := new(PillarProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarProtocol) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarProtocolList) DeepCopyInto(out *PillarProtocolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PillarProtocol, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarProtocolList.
func (in *PillarProtocolList) DeepCopy() *PillarProtocolList {
	if in == nil {
		return nil
	}
	out := new(PillarProtocolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarProtocolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarProtocolSpec) DeepCopyInto(out *PillarProtocolSpec) {
	*out = *in
	if in.NVMeOFTCP != nil {
		in, out := &in.NVMeOFTCP, &out.NVMeOFTCP
		*out = new(NVMeOFTCPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ISCSI != nil {
		in, out := &in.ISCSI, &out.ISCSI
		*out = new(ISCSIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NFS != nil {
		in, out := &in.NFS, &out.NFS
		*out = new(NFSConfig)
		**out = **in
	}
	if in.SMB != nil {
		in, out := &in.SMB, &out.SMB
		*out = new(SMBConfig)
		**out = **in
	}
	if in.MkfsOptions != nil {
		in, out := &in.MkfsOptions, &out.MkfsOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarProtocolSpec.
func (in *PillarProtocolSpec) DeepCopy() *PillarProtocolSpec {
	if in == nil {
		return nil
	}
	out := new(PillarProtocolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarProtocolStatus) DeepCopyInto(out *PillarProtocolStatus) {
	*out = *in
	if in.ActiveAgents != nil {
		in, out := &in.ActiveAgents, &out.ActiveAgents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarProtocolStatus.
func (in *PillarProtocolStatus) DeepCopy() *PillarProtocolStatus {
	if in == nil {
		return nil
	}
	out := new(PillarProtocolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarStorageClass) DeepCopyInto(out *PillarStorageClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarStorageClass.
func (in *PillarStorageClass) DeepCopy() *PillarStorageClass {
	if in == nil {
		return nil
	}
	out := new(PillarStorageClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarStorageClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarStorageClassList) DeepCopyInto(out *PillarStorageClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PillarStorageClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarStorageClassList.
func (in *PillarStorageClassList) DeepCopy() *PillarStorageClassList {
	if in == nil {
		return nil
	}
	out := new(PillarStorageClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarStorageClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarStorageClassSpec) DeepCopyInto(out *PillarStorageClassSpec) {
	*out = *in
	in.StorageClass.DeepCopyInto(&out.StorageClass)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(StorageClassOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarStorageClassSpec.
func (in *PillarStorageClassSpec) DeepCopy() *PillarStorageClassSpec {
	if in == nil {
		return nil
	}
	out := new(PillarStorageClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarStorageClassStatus) DeepCopyInto(out *PillarStorageClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarStorageClassStatus.
func (in *PillarStorageClassStatus) DeepCopy() *PillarStorageClassStatus {
	if in == nil {
		return nil
	}
	out := new(PillarStorageClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarStore) DeepCopyInto(out *PillarStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarStore.
func (in *PillarStore) DeepCopy() *PillarStore {
	if in == nil {
		return nil
	}
	out := new(PillarStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarStoreList) DeepCopyInto(out *PillarStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PillarStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarStoreList.
func (in *PillarStoreList) DeepCopy() *PillarStoreList {
	if in == nil {
		return nil
	}
	out := new(PillarStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarStoreSpec) DeepCopyInto(out *PillarStoreSpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarStoreSpec.
func (in *PillarStoreSpec) DeepCopy() *PillarStoreSpec {
	if in == nil {
		return nil
	}
	out := new(PillarStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarStoreStatus) DeepCopyInto(out *PillarStoreStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(StoreCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarStoreStatus.
func (in *PillarStoreStatus) DeepCopy() *PillarStoreStatus {
	if in == nil {
		return nil
	}
	out := new(PillarStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarVolumeState) DeepCopyInto(out *PillarVolumeState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarVolumeState.
func (in *PillarVolumeState) DeepCopy() *PillarVolumeState {
	if in == nil {
		return nil
	}
	out := new(PillarVolumeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarVolumeState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarVolumeStateList) DeepCopyInto(out *PillarVolumeStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PillarVolumeState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarVolumeStateList.
func (in *PillarVolumeStateList) DeepCopy() *PillarVolumeStateList {
	if in == nil {
		return nil
	}
	out := new(PillarVolumeStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PillarVolumeStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarVolumeStateSpec) DeepCopyInto(out *PillarVolumeStateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarVolumeStateSpec.
func (in *PillarVolumeStateSpec) DeepCopy() *PillarVolumeStateSpec {
	if in == nil {
		return nil
	}
	out := new(PillarVolumeStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PillarVolumeStateStatus) DeepCopyInto(out *PillarVolumeStateStatus) {
	*out = *in
	if in.PartialFailure != nil {
		in, out := &in.PartialFailure, &out.PartialFailure
		*out = new(PartialFailureInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.ExportInfo != nil {
		in, out := &in.ExportInfo, &out.ExportInfo
		*out = new(VolumeExportInfo)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PillarVolumeStateStatus.
func (in *PillarVolumeStateStatus) DeepCopy() *PillarVolumeStateStatus {
	if in == nil {
		return nil
	}
	out := new(PillarVolumeStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolOverrides) DeepCopyInto(out *ProtocolOverrides) {
	*out = *in
	if in.NVMeOFTCP != nil {
		in, out := &in.NVMeOFTCP, &out.NVMeOFTCP
		*out = new(NVMeOFTCPOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.ISCSI != nil {
		in, out := &in.ISCSI, &out.ISCSI
		*out = new(ISCSIOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.SMB != nil {
		in, out := &in.SMB, &out.SMB
		*out = new(SMBOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolOverrides.
func (in *ProtocolOverrides) DeepCopy() *ProtocolOverrides {
	if in == nil {
		return nil
	}
	out := new(ProtocolOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMBConfig) DeepCopyInto(out *SMBConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMBConfig.
func (in *SMBConfig) DeepCopy() *SMBConfig {
	if in == nil {
		return nil
	}
	out := new(SMBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMBOverrides) DeepCopyInto(out *SMBOverrides) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMBOverrides.
func (in *SMBOverrides) DeepCopy() *SMBOverrides {
	if in == nil {
		return nil
	}
	out := new(SMBOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassOverrides) DeepCopyInto(out *StorageClassOverrides) {
	*out = *in
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(BackendOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(ProtocolOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.MkfsOptions != nil {
		in, out := &in.MkfsOptions, &out.MkfsOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassOverrides.
func (in *StorageClassOverrides) DeepCopy() *StorageClassOverrides {
	if in == nil {
		return nil
	}
	out := new(StorageClassOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassTemplate) DeepCopyInto(out *StorageClassTemplate) {
	*out = *in
	if in.AllowVolumeExpansion != nil {
		in, out := &in.AllowVolumeExpansion, &out.AllowVolumeExpansion
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassTemplate.
func (in *StorageClassTemplate) DeepCopy() *StorageClassTemplate {
	if in == nil {
		return nil
	}
	out := new(StorageClassTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreCapacity) DeepCopyInto(out *StoreCapacity) {
	*out = *in
	if in.Total != nil {
		in, out := &in.Total, &out.Total
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Used != nil {
		in, out := &in.Used, &out.Used
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreCapacity.
func (in *StoreCapacity) DeepCopy() *StoreCapacity {
	if in == nil {
		return nil
	}
	out := new(StoreCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeExportInfo) DeepCopyInto(out *VolumeExportInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeExportInfo.
func (in *VolumeExportInfo) DeepCopy() *VolumeExportInfo {
	if in == nil {
		return nil
	}
	out := new(VolumeExportInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZFSBackendConfig) DeepCopyInto(out *ZFSBackendConfig) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZFSBackendConfig.
func (in *ZFSBackendConfig) DeepCopy() *ZFSBackendConfig {
	if in == nil {
		return nil
	}
	out := new(ZFSBackendConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZFSPropertyOverrides) DeepCopyInto(out *ZFSPropertyOverrides) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZFSPropertyOverrides.
func (in *ZFSPropertyOverrides) DeepCopy() *ZFSPropertyOverrides {
	if in == nil {
		return nil
	}
	out := new(ZFSPropertyOverrides)
	in.DeepCopyInto(out)
	return out
}
