//go:build e2e
// +build e2e

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package framework

// namespace.go — Kubernetes Namespace lifecycle helpers for pillar-csi e2e
// tests.
//
// Tests that exercise namespaced resources (PVCs, Pods, ConfigMaps, …) should
// create a dedicated Namespace per test (or per Describe block) so that
// resources are fully isolated and teardown is as simple as deleting the
// Namespace.
//
// Typical pattern with DeferCleanup (Ginkgo v2):
//
//	var ns *corev1.Namespace
//
//	BeforeEach(func() {
//	    var err error
//	    ns, err = framework.CreateTestNamespace(ctx, c, "my-test")
//	    Expect(err).NotTo(HaveOccurred())
//	    DeferCleanup(framework.EnsureNamespaceGone, ctx, c, ns.Name, 0)
//	})

import (
	"context"
	"fmt"
	"time"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/wait"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// ─────────────────────────────────────────────────────────────────────────────
// Namespace builder helpers
// ─────────────────────────────────────────────────────────────────────────────

// NewNamespace returns a Namespace object with the given name, ready to be
// passed to client.Create or framework.CreateNamespace.  The returned object
// is not yet created in the cluster.
func NewNamespace(name string) *corev1.Namespace {
	return &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Namespace CRUD operations
// ─────────────────────────────────────────────────────────────────────────────

// CreateNamespace creates a Kubernetes Namespace with the given name.
// It returns the created Namespace object (populated with server-assigned
// fields) or an error if the API server rejects the request.
//
// Use CreateTestNamespace when you want the server to generate a unique name
// from a prefix (avoiding naming conflicts between parallel tests).
func CreateNamespace(ctx context.Context, c client.Client, name string) (*corev1.Namespace, error) {
	ns := NewNamespace(name)
	if err := c.Create(ctx, ns); err != nil {
		return nil, fmt.Errorf("framework CreateNamespace %q: %w", name, err)
	}
	return ns, nil
}

// CreateTestNamespace creates a Namespace whose name is automatically
// generated by the API server from the given prefix (using the
// ObjectMeta.GenerateName mechanism).  The returned Namespace carries the
// server-assigned name in its ObjectMeta.Name field.
//
// Use this in BeforeEach / BeforeAll blocks to obtain a fresh, uniquely named
// namespace for each test so that parallel test runs do not collide.
//
// Example:
//
//	ns, err := framework.CreateTestNamespace(ctx, c, "csi-lifecycle")
//	// ns.Name might be "csi-lifecycle-7b4xz"
func CreateTestNamespace(ctx context.Context, c client.Client, prefix string) (*corev1.Namespace, error) {
	ns := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			GenerateName: prefix + "-",
		},
	}
	if err := c.Create(ctx, ns); err != nil {
		return nil, fmt.Errorf("framework CreateTestNamespace prefix=%q: %w", prefix, err)
	}
	return ns, nil
}

// DeleteNamespace deletes the Namespace identified by name.  It returns nil
// if the Namespace is already absent (idempotent).  Pass additional
// client.DeleteOptions to change the grace period or propagation policy.
func DeleteNamespace(ctx context.Context, c client.Client, name string, opts ...client.DeleteOption) error {
	ns := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{Name: name},
	}
	if err := c.Delete(ctx, ns, opts...); err != nil {
		if errors.IsNotFound(err) {
			return nil
		}
		return fmt.Errorf("framework DeleteNamespace %q: %w", name, err)
	}
	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Namespace wait helpers
// ─────────────────────────────────────────────────────────────────────────────

// WaitForNamespaceDeletion polls until the Namespace named name is fully
// removed from the API server (i.e. Get returns NotFound), or until the
// context is cancelled / timeout is exceeded.
//
// This function does not issue a Delete call — use DeleteNamespace or
// EnsureNamespaceGone to trigger deletion first.
//
// Pass 0 for timeout to use DefaultWaitTimeout.
func WaitForNamespaceDeletion(ctx context.Context, c client.Client, name string, timeout time.Duration) error {
	if timeout == 0 {
		timeout = DefaultWaitTimeout
	}

	ns := &corev1.Namespace{}
	err := wait.PollUntilContextTimeout(ctx, DefaultPollInterval, timeout, true,
		func(ctx context.Context) (bool, error) {
			if fetchErr := c.Get(ctx, client.ObjectKey{Name: name}, ns); fetchErr != nil {
				if errors.IsNotFound(fetchErr) {
					return true, nil
				}
				return false, fetchErr
			}
			return false, nil
		},
	)
	if err != nil {
		return fmt.Errorf("WaitForNamespaceDeletion %q: %w", name, err)
	}
	return nil
}

// EnsureNamespaceGone deletes the Namespace (if present) with a zero grace
// period and then blocks until it is fully removed from the API server.
// Pass 0 for timeout to use DefaultWaitTimeout.
//
// Suitable for AfterEach and DeferCleanup blocks where the Namespace may or
// may not exist at cleanup time.  Deleting the Namespace cascades to all
// namespaced resources it contains.
//
// Example:
//
//	DeferCleanup(framework.EnsureNamespaceGone, ctx, c, ns.Name, 5*time.Minute)
func EnsureNamespaceGone(ctx context.Context, c client.Client, name string, timeout time.Duration) error {
	if err := DeleteNamespace(ctx, c, name, client.GracePeriodSeconds(0)); err != nil {
		return err
	}
	return WaitForNamespaceDeletion(ctx, c, name, timeout)
}
