/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command helmcrds renders the Helm chart CRD template from the controller-gen
// output in config/crd/bases so the chart can never carry a second,
// hand-maintained copy of the CRD contract (names, shortNames, schema).
//
// Each CRD is emitted byte-for-byte except for one injected annotation,
// helm.sh/resource-policy: keep, so that a Helm upgrade or uninstall never
// deletes a CRD and cascade-deletes the stored custom resources.
//
// Usage (wired into `make manifests`):
//
//	go run ./hack/helmcrds -bases config/crd/bases -out charts/pillar-csi/templates/crds.yaml
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

const (
	header = "{{- /* Code generated by hack/helmcrds from config/crd/bases. DO NOT EDIT; run `make manifests`. */ -}}\n" +
		"{{- if .Values.installCRDs }}\n"
	footer = "{{- end }}\n"

	annotationsAnchor = "\nmetadata:\n  annotations:\n"
	keepAnnotation    = "    helm.sh/resource-policy: keep\n"
)

func main() {
	bases := flag.String("bases", "config/crd/bases", "directory holding controller-gen CRD YAML")
	out := flag.String("out", "charts/pillar-csi/templates/crds.yaml", "Helm template file to write")
	flag.Parse()

	rendered, err := render(*bases)
	if err != nil {
		fmt.Fprintf(os.Stderr, "helmcrds: %v\n", err)
		os.Exit(1)
	}
	err = os.WriteFile(*out, rendered, 0o644) //nolint:gosec // chart templates are world-readable source files
	if err != nil {
		fmt.Fprintf(os.Stderr, "helmcrds: write %s: %v\n", *out, err)
		os.Exit(1)
	}
}

func render(basesDir string) ([]byte, error) {
	files, err := filepath.Glob(filepath.Join(basesDir, "*.yaml"))
	if err != nil {
		return nil, fmt.Errorf("list CRDs in %s: %w", basesDir, err)
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("no CRD YAML found in %s", basesDir)
	}

	var buf bytes.Buffer
	buf.WriteString(header)
	for _, f := range files { // filepath.Glob returns lexically sorted paths: deterministic output
		crd, readErr := os.ReadFile(f) //nolint:gosec // path comes from a Glob over the repo's generated CRD directory
		if readErr != nil {
			return nil, fmt.Errorf("read %s: %w", f, readErr)
		}
		annotated, annotateErr := annotate(crd)
		if annotateErr != nil {
			return nil, fmt.Errorf("%s: %w", f, annotateErr)
		}
		buf.Write(annotated)
	}
	buf.WriteString(footer)
	return buf.Bytes(), nil
}

// annotate injects the keep annotation into a single controller-gen CRD
// document. It fails instead of guessing when the controller-gen layout it
// relies on changes, or when the content would be interpreted by Helm.
func annotate(crd []byte) ([]byte, error) {
	if bytes.Contains(crd, []byte("{{")) || bytes.Contains(crd, []byte("}}")) {
		return nil, errors.New("contains Helm template delimiters; cannot embed verbatim")
	}
	if bytes.Count(crd, []byte("\nkind: CustomResourceDefinition\n")) != 1 {
		return nil, errors.New("expected exactly one CustomResourceDefinition document")
	}
	if bytes.Count(crd, []byte(annotationsAnchor)) != 1 {
		return nil, fmt.Errorf("expected exactly one %q block emitted by controller-gen", annotationsAnchor)
	}
	annotated := bytes.Replace(crd, []byte(annotationsAnchor), []byte(annotationsAnchor+keepAnnotation), 1)
	if !bytes.HasSuffix(annotated, []byte("\n")) {
		annotated = append(annotated, '\n')
	}
	return annotated, nil
}
